Alfresco/docs-alfresco

- content-services/community/install/zip/index.md
FTR is an optional extra component that is not necessary in the core installation. It is covered elsewhere in the docs.
> Remove File Transfer Receiver from Installation

- insight-engine/1.4/config/sharding/create.md
It's required to add prefix namespace (cm in the sample) for "query" parameter
> Reindex documents by query

- insight-engine/latest/config/sharding/create.md
Added "cm" prefix to reindex by query sample.
> Required namespace prefix for reindexing documents by query

- content-services/latest/config/action.md
Correct the AMP file version to 6.2.2
> [DOCS-6163] Correct version of APS Action AMP file

- content-services/latest/index.md
- redirects/6.0/concepts/supported-platforms-ACS.html
- redirects/6.1/concepts/supported-platforms-ACS.html
- redirects/6.2/concepts/supported-platforms-ACS.html
- Improve redirects for ACS 6.x Supported platforms pages.
- Add link to "Legacy documentation" from the `/latest` ACS landing page, so that customers can navigate the documentation for ACS 5.2 and earlier versions.
> [DOCS-6177] Fix redirects for 6.x Supported Platforms pages

- content-services/6.0/install/containers/helm.md
- content-services/6.1/install/containers/helm-examples.md
- content-services/6.1/install/containers/helm.md
- content-services/6.2/install/containers/helm-examples.md
- content-services/6.2/install/containers/helm.md
- content-services/latest/install/containers/helm-examples.md
- content-services/latest/install/containers/helm.md
This one also updates ACS 7.0 helm chart info (and 6.0,6.1,6.2) and it's based on the content-services-7.0 branch.
> Helm chart update (Replaces Gavin's PR-#167)

- _data/toc/content-services.yaml
- content-services/community/install/index.md
- content-services/latest/install/ansible.md
- content-services/latest/install/index.md
- content-services/latest/upgrade/index.md
Fixes links to the following pages:
- Install: Overview
- Install: Install using Ansible / Ansible project in GitHub
- Admin: Securing your installation
Updates paragraph that links to new page for 'Securing your installation'
TODO: 'Deployment Support Policy’ link - this will be fixed once this branch is merged to master
> [DOCS-6190] Fix links to new content

- search-services/latest/install/index.md
Hi.
Parentheses were not being closed, which meant that some links were not being converted properly.
We've fixed that.
How about it?
> Link conversion fixed

- content-services/6.0/admin/audit.md
- content-services/6.0/admin/workflows.md
- content-services/6.1/admin/audit.md
- content-services/6.1/admin/workflows.md
- content-services/6.2/admin/audit.md
- content-services/6.2/admin/workflows.md
- content-services/community/admin/audit.md
- content-services/community/admin/workflows.md
- content-services/latest/admin/audit.md
- content-services/latest/admin/workflows.md
Following on from PR #225 (which corrects the Community `/admin/workflows.md` page), this PR fixes the same typos in other ACS versions plus a few more pages.
> Fix typos in various pages

- search-services/latest/admin/index.md
From SOLR 6 (Search Services 1.0), default port for Solr is 8983 instead of 8080.
> SOLR Default port is 8983 instead of 8080

- _includes/footer.html
Change URL for the Support Portal to one that correctly redirects to the Hyland Community portal
> Fix Customer Support Portal URL

- _config.yml
- _data/toc/transform-service.yaml
- content-services/6.2/install/containers/docker-compose.md
- content-services/6.2/install/containers/helm.md
- content-services/6.2/install/containers/index.md
- content-services/6.2/install/zip/index.md
- content-services/6.2/support/index.md
- content-services/latest/install/ansible.md
- content-services/latest/install/containers/docker-compose.md
- content-services/latest/install/containers/helm.md
- content-services/latest/install/containers/index.md
- content-services/latest/install/zip/index.md
- content-services/latest/support/index.md
- transform-service/1.2/install/index.md
- transform-service/1.3/admin/index.md
- transform-service/1.3/config/engine.md
- transform-service/1.3/config/extend.md
- transform-service/1.3/config/index.md
- transform-service/1.3/config/transformers.md
- transform-service/1.3/index.md
- transform-service/1.3/install/index.md
- transform-service/1.3/support/index.md
- transform-service/latest/install/index.md
- transform-service/latest/support/index.md
ITS Version bump to 1.4
Fix docs for ITS 1.3 and 1.4 to include additional install instructions for libs such as imagemagick and libreoffice.
ACS 6.2 and Latest updated with info on how to bootstrap IPTC Content Model.
ACS Support page update for 6.2 and Latest with ATS 1.4
> DOCS-6211 - ATS 1.4

- content-services/latest/install/zip/additions.md
Remove "Media Management" from _Installing integrations_ section to match the Supported platforms page.
> [DOCS-6309] Remove Media Management from ACS 7 integrations list

- _layouts/docs.html
- microsoft-office/1.1/index.md
- microsoft-office/1.2/index.md
- microsoft-office/1.3/index.md
- microsoft-office/latest/index.md
Note that some the products don't display a version drop-down selector in the Docs site, but have version "1.0" in the product title. In these cases, the content always reflects the latest release of that product:
- Alfresco Process Automation 1.0
- Alfresco Mobile Workspace 1.0
- Alfresco Content Services for Mobile 1.0
- Alfresco Support Handbook 1.0
> [DOCS-6308] Display currently selected version on product landing pages

- _data/toc/content-services.yaml
- content-services/6.2/install/ansible.md
- content-services/6.2/install/index.md
- content-services/latest/install/ansible.md
- Updates installation overview page  (similar to what was added in the ACS 7.0 docs)
- Links to new Ansible page (added #314 )
> [DOCS-6193] Update Installation overview page - 6.2

- _layouts/docs.html
Following on from #297, exclude the version number from the Support Handbook.
For some reason, we seem to have inherited extra version number injections in several subpages in the Support handbook. This PR now excludes the version number from the Support Handbook landing page and fixes the "extras" in the subpages. It also removes the version numbers from the following landing pages:
- Alfresco Process Automation
- Alfresco Mobile Workspace
- Alfresco Content Services for Mobile
> [DOCS-6328] Fix version numbers in Support Handbook pages

- content-services/6.2/support/index.md
- content-services/latest/support/index.md
This updates the Supported Platforms pages in Alfresco Content Services
> [DOCS-6325] Add Alfresco Content Connector for SAP Cloud 1.1 to ACS SP pages

- _config.yml
- _data/toc/process-services.yaml
I removed ``1.10`` from the config file which stopped the 1.10 branch from publishing correctly.
I've added it back in now.
(Fixes config changes in PR #278)
> [DOCS-6351] Add APS version workaround back in ``1.10``

- process-services/1.10/install/container.md
- process-services/1.11/install/container.md
- process-services/1.9/install/container.md
- process-services/latest/install/container.md
docker references updates used .x instead of a number at request of PM.,
> [DOCS-6350] docker references update

- content-services/5.2/using/content/files-folders.md
- content-services/5.2/using/content/index.md
- content-services/5.2/using/content/manage.md
- content-services/5.2/using/content/rules.md
- content-services/5.2/using/dashboard.md
- content-services/5.2/using/index.md
- content-services/5.2/using/permissions.md
- content-services/5.2/using/search.md
- content-services/5.2/using/share.md
- content-services/5.2/using/sites/features.md
- content-services/5.2/using/sites/index.md
- content-services/5.2/using/smart-folders.md
- content-services/5.2/using/tasks.md
These updates are part of ongoing improvements to the ACS 5.2 docs:
- Remove in-page tables of contents (TOCs)
- Remove statements about video tutorials in multiple files
- Add a single link to the **Tutorials** section in `/using/share.md`
- Correct text formatting in tables and other areas
> [DOCS-6373] Clean up Using Alfresco Share

- search-services/1.4/install/options.md
Having identical setting for both with or without mutual TLS is clearly a typo.
> Set mutual TLS solr.secureComms=https and port.ssl

- microsoft-outlook/2.7/config/index.md
- microsoft-outlook/latest/config/index.md
Removes the `highlightTexts` parameter in the sample configuration since it's no longer used. 
Applies to Alfresco Outlook Integration version 2.7 and above.
> [DOCS-6381] Remove highlightTexts parameter in sample config

- microsoft-outlook/latest/config/index.md
- Update required for Outlook Integration 2.8.1
- Minor fix to alignment of `<hr/>`
**Note:** This PR replaces PR #360.
> [DOCS-6395] Add wildcard capability for search configuration

- microsoft-outlook/latest/install/index.md
Adds a prerequisite for using Alfresco Search Services or Alfresco Search and Insight Engine 2.0 or above with Alfresco Outlook Integration 2.8.1 and above.
**Note:** This PR replaces draft PR #365.
> [DOCS-6401] Add prereq for using Search Services with Outlook Integration

- content-services/latest/install/ansible.md
- content-services/latest/install/containers/docker-compose.md
- content-services/latest/install/containers/helm.md
- content-services/latest/install/containers/index.md
- content-services/latest/install/zip/index.md
- transform-service/latest/install/index.md
- transform-service/latest/support/index.md
Version bump with lib updates.
Updated Supported Platforms page with links to IPTC model installs for ACS 7.0 and 6.2.
ACS 7.1 installation instructions updated: Removed IPTC model bootstrapping instructions, this model is included with ACS 7.1
> [DOCS-6418] ATS 1.4.1 version bump

- microsoft-outlook/2.7/config/index.md
- microsoft-outlook/latest/config/index.md
- microsoft-outlook/latest/install/index.md
- microsoft-outlook/latest/support/index.md
This branch will be merged to `master` once the release has been approved for GA release
Specific changes for Outlook Integration 2.8.1:
- #368 
- #369 - applies to both Search Services or Search and Insight Engine 
- #375 
- #390 
Maintenance only:
- #366
> [DOCS-6361] Add Alfresco Outlook Integration 2.8.1 docs 

- search-services/latest/config/keys.md
Fix a typo for SSL configuration in the Search Services documentation. This applies similar changes to  PR #433.
> [DOCS-6476] Correct keys.md

- desktop-sync/latest/config/index.md
This PR is the docs change for Alfresco Desktop Sync for Mac and Windows 1.8-M4 (INTERNAL RELEASE).
> [DOCS-6460] [MNT-21945] Add timezone configuration

- transform-service/latest/index.md
For ACS 7.1.1
* Remove ref to DAUs as these only com in with ACS 7.2
* Clean up description of failover transforms
> ATS 1.5 / ACS 7.1.1 (alan2)

- search-services/latest/admin/index.md
Fix the heading levels and thus the rendering of the toc/menu. This was still fine in the 1.4 version of the docs.
> [DOCS-6553] Fix heading levels

- content-services/5.2/install/index.md
- transformation-engine/2.2/install/sdk.md
This is a continuation of PR #544 with updates to older versions of the DTE docs
> [DOCS-6620] Remove references to source code access in DTE docs

- desktop-sync/1.8/config/index.md
- desktop-sync/latest/config/index.md
- Adds min and max values for configuration options in **Sync manager timers** table
- Fixes default value for `cmis.lowSpeedTime`
> [DOCS-6592] Add min and max values for configuration options

- insight-engine/1.4/config/properties.md
- insight-engine/1.4/config/sharding/create.md
- insight-engine/1.4/config/sharding/index.md
- insight-engine/latest/config/properties.md
- insight-engine/latest/config/sharding/create.md
- insight-engine/latest/config/sharding/index.md
This is fix for the following PR: Move solr related prop to acs alfresco-global.properties #168
> [DOCS-6612] Moved solr shard prop config from general solr config to alfresco acs config

- .github/workflows/sandbox.yml
Our build pipelines are taking longer and longer to process. This is an initial test to reduce the duration of the Sandbox workflow (for commits to a `feature-branch`). It’ll be a good test to see how long the checks take for Sandbox only, especially for multiple commits to the same branch, which take longer for each iteration.
> [DOCS-6691] Pipeline improvement - reduce sandbox workflow duration

- content-services/latest/upgrade/index.md
To apply the recommended patch, the value needs to be false and not true.
> [MNT-22706] Apply recommended patch needs a value of false

- content-services/7.0/upgrade/index.md
- content-services/7.1/upgrade/index.md
- content-services/latest/upgrade/index.md
This update completes the fix suggested in PR #475 and also requested in MNT-22706: 
> To apply the patch, an admin should set the following Alfresco global property to `false`:
> `system.new-node-transaction-indexes.ignored=false`
> [MNT-22706] Fix value for applying recommended patch

- content-services/5.2/support/index.md
- content-services/6.0/support/index.md
- content-services/6.1/support/index.md
- content-services/6.2/support/index.md
- content-services/7.0/support/index.md
- content-services/7.1/support/index.md
- content-services/latest/support/index.md
This updates the ACS Supported platforms pages so that they're aligned with the individual services, integrations, and applications. Relates to the upcoming releases only, and continues on from PR #641.
> [DOCS-6709] Update compatible versions in Supported platforms pages

- content-services/7.1/develop/rest-api-guide/folders-files.md
- content-services/latest/develop/rest-api-guide/folders-files.md
Added note to 7.1 and 7.2 ReST API docs that API calls will not allow aspects or properties contained in the sys: namespace.
> [DOCS-6711] Added warning note that sys: namespace is not allowed in ReST API calls for ACS 7.1 and 7.2

- process-automation/latest/develop/index.md
The swagger-ui url changed from /swagger-ui.html to /swagger-ui/index.html after migration from Springfox to Springdoc. This should be reflected in the documentation.
> [AAE-8650] fix swagger ui url

- search-services/1.3/config/filtered.md
Character : must be escaped in properties file, like in the "old" documentation : https://docs.alfresco.com/content-services/6.2/admin/share-admin-tools/#search-manager
> [DOCS-6746] Custom facets : Missing \ in properties qnames

- insight-engine/1.0/config/filtered.md
- insight-engine/1.1/config/filtered.md
- insight-engine/1.4/config/filtered.md
- insight-engine/latest/config/filtered.md
- search-services/1.4/config/filtered.md
- search-services/latest/config/filtered.md
This PR completes the updates started in PR #298.
The character ":" must be escaped in properties file, as in older ACS documentation such as: 
https://docs.alfresco.com/content-services/6.2/admin/share-admin-tools/#search-manager.
> [DOCS-6746] Fix default and custom filtered search configuration properties

- content-services/latest/support/index.md
- intelligence-services/1.3/config/comprehend.md
- intelligence-services/1.3/index.md
- intelligence-services/1.3/install/index.md
- intelligence-services/1.3/using/index.md
- intelligence-services/latest/config/comprehend.md
- intelligence-services/latest/config/index.md
- intelligence-services/latest/index.md
- intelligence-services/latest/install/index.md
- intelligence-services/latest/support/index.md
- For AIS 1.3.x: updated links to point to Content Services 7.1 docs.
- For AIS 1.4.4: updated supported AIS version in Content Services 7.2 Supported platforms page, and changed references to Digital Workspace 2.8, and Transform Service 1.5. The previous versions should be backward compatible.
> [DOCS-6741] Alfresco Intelligence Services 1.4.4

- _data/toc/transform-service.yaml
- transform-service/latest/config/add-tengine-trouter.md
Note that page has been renamed (from latest/config/transformers/ to latest/config/add-tengine-trouter/).
> [DOCS-6754] Adding page for add T-Engine to T-Router to ATS 1.5

- content-services/5.2/admin/auth-sync.md
- content-services/6.0/admin/auth-sync.md
- content-services/6.1/admin/auth-sync.md
- content-services/6.2/admin/auth-sync.md
- content-services/7.0/admin/auth-sync.md
- content-services/7.1/admin/auth-sync.md
- content-services/latest/admin/auth-sync.md
This a fix for contributed PR #280
> [DOCS-6719] Use AuthNegotiateDelegateAllowlist instead of AuthNegotiateDelegateWhitelist for Chrome

- identity-service/1.1/tutorial/sso/ldap.md
- identity-service/1.1/tutorial/sso/saml.md
- identity-service/1.2/tutorial/sso/ldap.md
- identity-service/1.2/tutorial/sso/saml.md
- identity-service/1.3/tutorial/sso/ldap.md
- identity-service/1.3/tutorial/sso/saml.md
- identity-service/1.4/tutorial/sso/ldap.md
- identity-service/1.4/tutorial/sso/saml.md
- identity-service/1.5/tutorial/sso/ldap.md
- identity-service/1.5/tutorial/sso/saml.md
- identity-service/1.6/tutorial/sso/ldap.md
- identity-service/1.6/tutorial/sso/saml.md
- identity-service/1.7/tutorial/sso/ldap.md
- identity-service/1.7/tutorial/sso/saml.md
- identity-service/latest/config/index.md
- identity-service/latest/install/zip/index.md
- identity-service/latest/tutorial/sso/ldap.md
- identity-service/latest/tutorial/sso/saml.md
- identity-service/latest/upgrade/index.md
- Upgrade Keycloak docs links to 18.0
- Remove Java 8 in zip installation page
- Fix spacing in Single Sign On Guides
> [DOCS-6737] Updates for Identity Service 1.8 release

- content-services/latest/develop/sdk.md
This PR addresses the issue raised in https://github.com/Alfresco/alfresco-sdk/issues/636.
> [DOCS-6794] Fixed enterprise docker image names in SDK 4.4 pom.xml config

- transform-service/1.2/install/index.md
- transform-service/1.3/install/index.md
- transform-service/1.4/install/index.md
- transform-service/latest/install/index.md
ATS host URL change in command line start, replaces #711
> [DOCS-6394] ATS host URL change in command line start

- content-services/5.2/admin/import-transfer.md
- content-services/6.0/admin/import-transfer.md
- content-services/6.1/admin/import-transfer.md
- content-services/6.2/admin/import-transfer.md
- content-services/7.0/admin/import-transfer.md
- content-services/7.1/admin/import-transfer.md
- content-services/community/admin/import-transfer.md
- content-services/latest/admin/import-transfer.md
Some fields are shown in extra columns but they need to combined into a single column:
Idle | In Progress
Yes | No | n/a
AM | PM
See formatting in archived page: 
https://github.com/Alfresco/docs-alfresco/blob/master/_archive/content-services/5.2/references/bulk-import-table.md#bulk-import-tool-fields-and-values
> [DOCS-6540] Fix table for bulk import fields and values

- content-services/5.2/admin/security.md
- content-services/5.2/admin/workflows.md
- content-services/6.0/admin/security.md
- content-services/6.1/admin/security.md
- content-services/6.2/admin/security.md
- content-services/6.2/admin/workflows.md
- content-services/7.0/admin/security.md
- content-services/7.0/install/zip/additions.md
- content-services/7.1/admin/security.md
- content-services/7.1/develop/rest-api-guide/folders-files.md
- content-services/7.1/install/zip/additions.md
- content-services/community/admin/security.md
- content-services/community/admin/workflows.md
- content-services/community/install/zip/additions.md
- content-services/latest/admin/security.md
- content-services/latest/develop/rest-api-guide/folders-files.md
- content-services/latest/install/zip/additions.md
- Fixes typos for NTLM & BPMN
- Fix codeblocks within **Notes**
- Fix link format in ACS ZIp install - additional software page
> [DOCS-6619] Fix typos in Content Services docs

- search-services/latest/using/index.md
Fix missing operator '|' and add missing character escaping for CMIS query examples to work correctly
- Fixed the missing operator '|' that completes the correct query. 
- Search like 'big must occur and dog should occur' would be return only if term is prefixed with '|' , example:  `big AND |dog`
This fix can be compared with: https://github.com/Alfresco/docs-alfresco/blob/master/content-services/5.2/develop/alfresco-full-text-search-ref.md?plain=1#L425
- Added missing character escaping for CMIS query examples to work correctly.
- CMIS contains had missing escaping character. Query result in parsing error without escaping character.
Examples from here works: https://github.com/Alfresco/docs-alfresco/blob/master/content-services/5.2/develop/alfresco-full-text-search-ref.md?plain=1#L463
> [DOCS-6768] Fix missing operator '|' and add missing character escaping for CMIS query examples

- insight-engine/1.0/using/sql/syntax.md
- insight-engine/1.1/using/sql/syntax.md
- insight-engine/1.4/using/sql/syntax.md
- insight-engine/latest/using/sql/syntax.md
- search-services/1.3/using/index.md
- search-services/1.4/using/index.md
This PR completes the updates started by @abhinavmishra14 in PR #664 :
- Fix missing operator '|' to correctly complete the query
- Add missing character escaping for CMIS query examples to work correctly
⚠️ TODO: Verify update mentioned in https://github.com/Alfresco/docs-alfresco/pull/664#discussion_r921083179
> [DOCS-6768] Fix missing characters for CMIS query examples

- google-drive/latest/install/index.md
For a first visiting customer it is not very intuitive to search in Support->Alfresco Downloads->GoogleDocsIntegration. Providing a direct link for this page it is more efficient for the goal of installing the amps
> [DOCS-6844] Provide the exact link for Google Docs Integration package download

- redirects/7.2/concepts/intrans-metadata-conf-patch.html
- redirects/7.2/concepts/intrans-metadata-feature.html
Some of the original redirects from the Admin Console were missed in the site launch. Affects Search Services docs.
> [DOCS-6841] Add new Content Services 7.2 redirects

- content-services/7.1/support/index.md
- content-services/latest/support/index.md
- saml-module/latest/support/index.md
SAML Module 1.2.3 added new SAML version to content services, and SAML listed as supported for ACS 7.1 and 7.2.
> [DOCS-6830] SAML Module 1.2.3 added

- content-services/7.1/support/index.md
- content-services/latest/support/index.md
- google-drive/latest/support/index.md
Updated versions supported for ACS 7.1 and 7.2, and for GoogleDocs 3.2.2
> [DOCS-6831] GoogleDocs Integration 3.2.2

- transform-service/1.2/install/index.md
- transform-service/1.3/install/index.md
- transform-service/1.4/install/index.md
- transform-service/latest/install/index.md
Update the Transform Engine (T-Engine) notes to clarify that LibreOffice, ImageMagick and Alfresco PDF Renderer binaries must be installed with the T-Engine for it to be fully functional.
Most users that i know, were confused at this point and tend to miss important steps outlined in prerequisites.
> [DOCS-6858] Update Transform Engine notes with additional clarification

- _data/toc/search-services.yaml
- search-services/latest/upgrade/breaking-changes-1.x.md
Content Model indexation for secondary properties of type `d:content` is unsupported in Search Services 2.x
> DOCS-6863 Add unsupported features section for Search Services 2.x

- sap-cloud/latest/support/index.md
- sap/latest/support/index.md
Fix the compatible ACS versions for SAP products:
- Alfresco Content Connector for SAP Applications 5.2 
- Alfresco Content Connector for SAP Cloud 1.2
> [DOCS-6872] Add Content Services 7.2.x as compatible version for SAP products

- search-services/latest/upgrade/index.md
The note now matches the equivalent page in the Alfresco Search and Insight Engine docs: https://github.com/Alfresco/docs-alfresco/blob/master/insight-engine/latest/upgrade/index.md?plain=1#L45
> Fix final note in Alfresco Search Services upgrade page

- content-services/7.0/support/index.md
- content-services/7.1/support/index.md
- content-services/latest/support/index.md
Update Desktop Sync 1.13 compatibility in the ACS 7.0 - 7.2 Supported platforms pages
> [DOCS-6861] Add Desktop Sync 1.13 compatibility

- content-services/6.2/support/index.md
- content-services/7.0/support/index.md
- content-services/7.1/support/index.md
- content-services/latest/support/index.md
This updates the ACS Supported platforms pages so that they're aligned with the individual services, integrations, and applications. See the individual commits for more details:
- #762 
- #785 
- #788
> [DOCS-6870] Update Content Services Supported Platforms pages

- search-services/latest/install/options.md
In the current documentation says, that in ordner to use the HTTP communication method with "secret" word in request header  you have to install Alfresco Content Services 7.1 or above.
In Reference to 
https://community.hyland.com/en/blog/posts/83712-upgrading-to-alfresco-content-services-7-2 the "secret" communcation method feature is only available in ACS 7.2 and above.
I know that it was tested initially by @aborroy with ACS7.1, see https://github.com/AlfrescoLabs/alfresco-solr-comm and he showed this "secret" communication method feature in https://www.youtube.com/watch?v=BSNJz6nd8Xg
but as far as we now, this feature is only available for customers with ACS 7.2. and above.
Could you please verify this?
> Solr Communication Method Secret with ACS 7.2

- _config.yml
If you go to any [Alfresco Document Transformation Engine v2.2 docs page](https://docs.alfresco.com/transformation-engine/2.2/) and then try to switch to the `latest` docs by selecting **2.3 latest** from the dropdown, it just switches back to showing the earlier `2.2` release docs. This is because the **latest** version is set twice, for `2.2 `and `2.3`. This PR removes the latest setting from the 2.2 version.
> [DOCS-7013] Fix site config for latest DTE 2.3 docs

- content-services/7.2/support/index.md
- content-services/latest/support/index.md
Supported with ACS 7.3 and 7.2
> [DOCS-6999] Update Supported Platforms page (Google Docs Integration 3.3) 

- content-services/6.2/install/containers/helm.md
- content-services/7.0/install/containers/helm.md
- content-services/7.1/install/containers/helm.md
- content-services/7.2/install/containers/helm.md
- content-services/latest/install/containers/helm.md
Helm install updates for 6.2 to latest based on following external PRs:
* nodegroup is not linux-nodes, need to find name of node group created as part of cluster creation: #356 
* Changes needed for acs-ingress install: #357 
* Fixes for nfs-provisioner in K8 1.20 and later: #358
> [DOCS-6747] ACS Helm install updates based on PR #356, #357, #358

- content-services/latest/install/containers/customize.md
- content-services/latest/install/containers/docker-compose.md
- content-services/latest/install/zip/additions.md
- content-services/latest/install/zip/amp.md
- content-services/latest/install/zip/index.md
- content-services/latest/install/zip/tomcat.md
Applies updates for the distribution zip installation method.
⚠️ Updates for the Enterprise Docker Compose (via the Download Trial), Helm and Ansible deployments will be addressed separately.
> [DOCS-6966] Updates to ACS 7.3 Install section

- content-services/community/install/containers/docker-compose.md
This PR updates the ACS Community Docker Compose page.
Split off https://github.com/Alfresco/docs-alfresco/compare/DOCS-7005
> [DOCS-7005] Content Services 7.3 Community docker image updates

- search-services/latest/config/replication.md
That class has been removed from Search Services 2.0, anyone using that configuration will get an error message.
> [DOCS-6978] Fix reference to missing class (since Search Services 2.0)

- content-services/7.0/support/index.md
- content-services/7.1/support/index.md
- content-services/7.2/support/index.md
This PR corrects the Alfresco Federation Services (AFS) compatibility with Alfresco Content Services 7.0 - 7.2
> [DOCS-6952][DOCS-6696] Update Federation Services compatibility with Content Services

- redirects/7.3/concepts/auth-alfrescontlm-intro.html
Since there's a space at the end of the redirect path in the source file, the redirect only goes to the ACS docs root (https://docs.alfresco.com/content-services/latest/) instead of `/content-services/latest/admin/auth-sync/`. This ticket removes the trailing space so the redirect will work properly.
> [DOCS-7110] Remove trailing space in redirect path

- identity-service/latest/tutorial/sso/ldap.md
- identity-service/latest/tutorial/sso/saml.md
This PR removes some leftover content from the second bullet point in the SAML (Step 6) and LDAP (Step 3) pages. Affects the SSO Guide v2 for ACS 7.3 and above
> [DOCS-7107] Remove leftover content from SSO Guide for ACS 7.3 and above

- search-services/latest/config/keys.md
The original commands don't work, different types of quote are used around 'password': ./run.sh -keystorepass “password" -truststorepass “password"
> [DOCS-7137] Update keys

- content-services/5.2/install/index.md
- transformation-engine/2.2/index.md
- transformation-engine/latest/index.md
This PR clarifies the supported Microsoft Office file types in the Alfresco Document Transformation docs and removes related duplicate links in the Alfresco Content Services 5.2 docs.
> [DOCS-5422] Clarify supported MS Office file types in DTE docs

- identity-service/latest/support/index.md
Update page based on the components tested with Alfresco Content Services 7.3
> [DOCS-7031] Fix Supported platforms page for Identity Service 1.8

- content-services/latest/develop/oop-ext-points/events.md
Add description and property to disable the events from being triggered and sent to ActiveMQ.
> [DOCS-7099] Content Services 7.4 Add description to disable event2

- content-services/latest/admin/auth-sync.md
In the ACS 7.4 the Keycloak Adapter has been replaced by Spring Security components.
> [DOCS-7214] ACS 7.4 Keycloak Adapter migration

- _data/toc/content-accelerator.yaml
- content-accelerator/latest/install/sso.md
This PR adds a new SSO feature for Content Accelerator 3.5.1+ and updates the configuration for the existing feature.
> [DOCS-7248] Add new SSO feature for Content Accelerator 3.5.1

- content-services/7.0/install/containers/index.md
- content-services/7.1/install/containers/index.md
- content-services/7.2/install/containers/index.md
- content-services/7.3/install/containers/index.md
- content-services/latest/install/containers/index.md
Fixes the NGINX container name in Alfresco Content Services 7.0-7.4, following on from #1049. Also fixes what's deployed in Content Services 7.2-7.4. The Community docs will be fixed in a separate PR.
> [DOCS-7041] Fix NGINX container name and what's deployed

- content-services/latest/support/index.md
This PR has the following changes:
- Update compatible versions in Alfresco Content Services 7.4 SP page
- Add Alfresco Control Center & replace ADF 5.x with ADF 6.x
- Replace the old link to '_contact Support_' with a link to the relevant page in the Support Handbook
> [DOCS-7285] Update Content Services 7.4 Supported platforms page

- search-enterprise/latest/using/unsupported.md
PARENT, PRIMARYPARENT and ANCESTOR are now all supported. There is no support for secondary parent-child relationships yet.
Add examples of how to rewrite certain unsupported queries to work around issues.
> ACS-4369 Support for path features.

- content-services/5.2/using/content/manage.md
- content-services/5.2/using/dashboard.md
- content-services/6.0/using/content/manage.md
- content-services/6.1/using/content/manage.md
- content-services/6.2/using/content/manage.md
- content-services/7.0/using/content/manage.md
- content-services/7.1/using/content/manage.md
- content-services/7.2/using/content/manage.md
- content-services/7.3/using/content/manage.md
- content-services/community/using/content/manage.md
- content-services/latest/using/content/manage.md
This PR removes the sentence “This video shows ... “
This statement no longer applies as the videos are no longer embedded in these pages - they were moved to the **Tutorials** section a long while ago.
> [DOCS-6579] Remove statement about embedded videos in ACS Using docs

- desktop-sync/latest/using/app-menu.md
This PR moves the **Recent Files** section further up the page for Mac, so the menu order matches the options in the recently released app. No content changes.
> [DOCS-7311] Move Recent Files section for Mac

- transform-service/1.3/install/index.md
- transform-service/1.4/install/index.md
- transform-service/1.5/install/index.md
- transform-service/2.0/install/index.md
- transform-service/2.1/install/index.md
- transform-service/latest/install/index.md
The release tag is only mentioned in the Alfresco Transform Service docs.
> [DOCS-7310] Update example release tag for Content Services 7.4

- content-services/latest/support/index.md
This PR adds Rocky Linux 8.7 and updates Red Hat Enterprise Linux versions.
> [DOCS-7239] Add Rocky Linux to updated supported ACS stack

- redirects/process-services1.10/topics/licensing.html
- redirects/process-services1.11/topics/licensing.html
- redirects/process-services1.6/topics/licensing.html
- redirects/process-services1.7/topics/licensing.html
- redirects/process-services1.8/topics/licensing.html
- redirects/process-services1.9/topics/licensing.html
Fixes the redirects from the old Alfresco Docs site links, like `process-services1.11/topics/licensing.html`.
⚠️ Need to test if the anchor links in staging or production.
> [DOCS-7365] Fix redirects for APS licensing links

- search-enterprise/3.0/using/unsupported.md
- search-enterprise/3.1/using/unsupported.md
- search-enterprise/3.2/using/unsupported.md
- search-enterprise/latest/using/unsupported.md
SEARCH-2794 Backport documentation of lack of support for ANAME to Alfresco Search Enterprise (ASE) 3.2.
Fix description about behaviour with unsupported fields in ASE 3.0, 3.1 and 3.2.
> [ACS-4914] Alfresco Search Enterprise does not support the member keyword for categories

- insight-engine/latest/config/transactional.md
- search-services/latest/config/transactional.md
You may want to add some additional insight around the runAsSytem  change.  I think that the values can also be set on a per query basis vi the JavaScript library, but I did not test it.
See more information here. https://community.hyland.com/en/customer-portal/38833/support-cases/00757594
> [DOCS-7323] Changes made based on NASA JPL support case 00757594

- saml-module/latest/config/alfresco.md
After a conversation with @Leonardo Mattioli, I think it is better to adjust the description of the cookie used for rest api calls. It is not so 'automatic' as it looks at first read
Following the documentation he was getting `401`. 
A more detailed explaination is provided on the same page in 'Developer Section' https://docs.alfresco.com/saml-module/latest/develop/#authenticate-users-in-an-application-using-saml-via-the-rest-api
> [DOCS-7376] Revise cookie usage in SAML Module docs

- content-services/7.4/admin/control-center.md
- content-services/7.4/install/containers/docker-compose.md
This PR updates the current ACS Download Trial  in the Alfresco Content Services 7.4 and Alfresco Governance Services 7.4 docs to *Version 7.4 - May 2023*.
> [DOCS-7283] Update ACS 7.4 Download Trial details

- enterprise-viewer/latest/config/files.md
The property (`minPagesToDefafultSectionModeOn`) is misspelled in the code so we need the misspelling to be carried over in the documentation so that the property override to work correctly for customers.
> [DOCS-7474] Revise property name in Enterprise Viewer docs

- content-accelerator/latest/configure/actions.md
- content-accelerator/latest/install/install-guide.md
This commit is intended for _[DOCS-7089] Download Document Enhancement_ and review for this commit is required. _[DOCS-7124] Update Content Accelerator install configuration steps_ has appeared in this commit due to an error and has been reviewed in another commit. 
Regarding DOCS-7089, in the **Configuration Options for Download Document** section, I have removed the **Available Rendition Types** topic but retained the **Downloaded File Name** topic before adding the new settings. 
[DOCS-7089]: https://alfresco.atlassian.net/browse/DOCS-7089?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DOCS-7124]: https://alfresco.atlassian.net/browse/DOCS-7124?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DOCS-7089] Download Document Enhancement

- content-services/latest/support/index.md
As per current [ACS supported platforms](https://alfresco.atlassian.net/wiki/spaces/PO/pages/1074790451/ACS+Supported+Platforms+Roadmap)
> [DOCS-7512] Drop deprecated centos 8 and minor version in RHEL

- content-accelerator/latest/install/install-guide.md
- enterprise-viewer/latest/install/index.md
This PR also updates references to the deployment resources required in the Alfresco Content Accelerator 3.6 installation guide
> [DOCS-7511] Fix versions in Content Accelerator and Enterprise Viewer 3.6 docs

- search-services/latest/using/index.md
Update to documentation on search with "TEXT". From my observations it will search fields of type d:text and d:mltext in addition to the fields of type d:content
> [DOCS-7525] Update index.md

- content-services/latest/support/index.md
Internet Explorer 11 is not supported in ACS 23.1 - deleted from a list of supported browsers
> [DOCS-7540] Remove Internet Explorer 11 from supported browsers

- search-services/latest/config/properties.md
**_Updated the properties.md page according to the following instructions:_**
At this page: https://docs.alfresco.com/search-services/latest/config/properties/  there are some error.
These documented properties are no more used:
alfresco.metadata.skipDescendantDocsForSpecificTypes
alfresco.metadata.ignore.datatype.0
alfresco.metadata.ignore.datatype.1
They were still valid, but no more used in the code after this pull request 5 years ago https://github.com/Alfresco/SearchServices/pull/72 
I haven’t traced were all these modifications were introduced in the code, I guess with version 2.0 of Search Services.
These properties are, in my opinion, useful but not documented:
alfresco.cascade.tracker.nodeBatchSize:  This property is used for batch fetching cascade updates during indexing, for …
> [DOCS-7200] Update Search Services configuration properties

- identity-service/latest/tutorial/sso/saml.md
Ref: OPSEXP-2335
Adding `oauth2` prefix in the table of properties to make it clear that all those properties are not at the same level - as can be seen below on the example
> [OPSEXP-2335] Fix property namespace for configuring SSO ADF apps

- content-services/latest/develop/oop-sdk.md
Documentation was updated to reflect the change in the artifact name for the ACS Java ReST API.  I noticed these is also an APA artifact as well so I don't know if this documentation needs to be updated to reflect that or not (I am assuming not since neither workflow or APA are mentioned on this page).
> [DOCS-7069] Java ReST API artifact changed name in SDK 5.2.0

- content-services/7.2/admin/cluster.md
This PullRequest commit updates to custom-slingshot-application-context.xml for acs 7.2.x to correct the xsi:schemaLocation to point to the correct hazelcast-spring<versionstring>.md.
PullRequest is related to the internal support cases
00951842 - Alfresco 6.2.1 - Share Cluster - Documentation and sample file not up to date
01623221 - Hazelcast Share Cluster example configuration is outdated and prevents acs startup
The custom-slingshot-application-context.xml example on
https://docs.alfresco.com/content-services/7.2/admin/cluster/#setting-up-an-alfresco-share-cluster
is outdated. If you use an acs 7.2 cluster server without internet connection, you'll end up with the following message in the share.log which prevents acs/tomcat to start up:
```
15:57:30,836 WARN …
```
> [DOCS-7372] Support Case 01623221 - Update Hazelcast Share Cluster example configuration SchemaLocation

- search-enterprise/3.1/upgrade/index.md
- search-enterprise/3.2/upgrade/index.md
- search-enterprise/3.3/upgrade/index.md
- search-enterprise/latest/upgrade/index.md
Modified step 5 of **Zero downtime upgrade** heading in the **Upgrade to Search Enterprise** page.
> [DOCS-7572] Incorrect environment reference in Search Enterprise

- identity-service/latest/tutorial/sso/ldap.md
- identity-service/latest/tutorial/sso/saml.md
Providing the secret field inside the oauth config example of a webapp is not suggesting a good security practice
related PR https://github.com/Alfresco/alfresco-applications/pull/496
> [DOCS-7583] Drop secret key from adw example json config

- process-automation/latest/model/triggers.md
Reverts Alfresco/docs-alfresco#1338 as it's not been enabled in APA yet
> Revert "Add secured parameter for INCOMING_WEBHOOK"

- content-services/latest/support/index.md
> [DOCS-7587] Add ATS 4.0 compatibility back into ACS 23.1 table

- search-services/latest/upgrade/breaking-changes-1.x.md
Two points....
1. The change is only needed if you have to search the d:content properties (in many cases, the property is a rendition with no additional text content and would not need to be searched)
2. It may be better to consider using a child-association rather than an association.  In many cases this content is part of the object.  You would want the secondary node to be deleted if the primary node is deleted.
> [DOCS-7526] Update breaking-changes-1.x.md

- _data/toc/sap-cloud.yaml
This PR fixes the blank table of contents for the latest SAP Cloud Connector 2.0 documentation
> [DOCS-7679] Fix missing TOC in SAP Cloud 2.0 docs

- search-enterprise/3.2/support/index.md
- search-enterprise/3.3/support/index.md
- search-enterprise/latest/support/index.md
Removed the Alfresco Elasticsearch Connector instances as it is synonymous to Alfresco Search Enterprise. 
To maintain consistency, I did not modify the Elasticsearch server versioning format as there are other Alfresco component versions listed in the same way in other Supported Platforms pages.
> [DOCS-7635] Update Supported Platforms for Search Enterprise

- content-services/latest/support/index.md
This PR includes compatibility changes in Alfresco Content Services 23.x for:
- Alfresco Desktop Sync 1.18 
- Alfresco Intelligence Services 3.1.3
> [DOCS-7710][DOCS-7708] Add & update compatibility in ACS 23.x

- content-services/7.2/support/index.md
This PR includes compatibility changes in Alfresco Content Services 7.2 for:
- Alfresco Desktop Sync 1.18 
- Alfresco Sync Service 3.11.3
- Alfresco Intelligence Services 3.1.3
> [DOCS-7710][DOCS-7723] Add & update compatibility in ACS 7.2

- content-services/7.3/support/index.md
This PR includes compatibility changes in Alfresco Content Services 7.3 for:
- Alfresco Desktop Sync 1.18 
- Alfresco Sync Service 3.11.3
- Alfresco Salesforce Connector 2.4
- Alfresco Google Docs Integration 3.4
- Alfresco Intelligence Services 3.1.3
> [DOCS-7710][DOCS-7723] Add & update compatibility in ACS 7.3

- content-services/7.4/support/index.md
This PR includes compatibility changes in Alfresco Content Services 7.4 for:
- Alfresco Desktop Sync 1.18 
- Alfresco Sync Service 3.11.3
- Alfresco Intelligence Services 3.1.3
> [DOCS-7710][DOCS-7723] Add & update compatibility in ACS 7.4

- search-enterprise/latest/config/index.md
In the mediation-filter.yml example some typo may mislead the reader
> [DOCS-7722] Typos in index.md

- content-services/7.0/develop/rest-api-guide/index.md
- content-services/7.0/develop/rest-api-guide/install.md
- content-services/7.0/develop/sdk.md
- content-services/7.0/install/ansible.md
- content-services/7.1/develop/rest-api-guide/index.md
- content-services/7.1/develop/rest-api-guide/install.md
- content-services/7.1/develop/sdk.md
- content-services/7.1/install/ansible.md
- content-services/7.2/develop/rest-api-guide/index.md
- content-services/7.2/develop/rest-api-guide/install.md
- content-services/7.2/develop/sdk.md
- content-services/7.2/install/ansible.md
- content-services/7.3/develop/rest-api-guide/index.md
- content-services/7.3/develop/rest-api-guide/install.md
- content-services/7.3/develop/sdk.md
- content-services/7.3/install/ansible.md
- content-services/7.4/develop/rest-api-guide/index.md
- content-services/7.4/develop/rest-api-guide/install.md
- content-services/7.4/develop/sdk.md
- content-services/7.4/install/ansible.md
- content-services/latest/develop/rest-api-guide/index.md
- content-services/latest/develop/rest-api-guide/install.md
- content-services/latest/develop/sdk.md
- content-services/latest/install/ansible.md
**Noteworthy:** Links to artifacts.alfresco.com access the same service as nexus.alfresco.com.
> [DOCS-7800] Fix Nexus broken links in ACS 7.0 +

- _config.yml
- _data/toc/content-services-tutorial.yaml
- _data/toc/content-services.yaml
- _data/toc/governance-services-tutorial.yaml
- _data/toc/governance-services.yaml
- _data/toc/process-services.yaml
- content-services/latest/index.md
- content-services/latest/support/index.md
- governance-services/latest/support/index.md
- process-services/latest/support/index.md
These are the **latest** versions documented in GitHub and published to the [Alfresco Docs site](https://docs.alfresco.com/), and will be displayed as follows:
Latest Version in GitHub Docs | Documented Product Versions
-- | --
ACS 23.2 | ACS 23.2 and ACS 23.1
AGS 23.2 | AGS 23.2 and AGS 23.1
APS 24.2 | APS 24.2 and APS 24.1
New versions of these products will be published to the [Hyland Documentation Portal](https://support.hyland.com/).
> [DOCS-7828] Update to latest release versions in Alfresco Docs site

- content-services/7.0/config/repository.md
- content-services/7.1/config/repository.md
- content-services/7.2/config/repository.md
- content-services/7.3/config/repository.md
- content-services/7.4/config/repository.md
- content-services/latest/config/repository.md
For version 7.0, 7.1, 7.2, 7.3, 7.4, latest (23.x)
- removed outdated paragraph about #customize-content-transformations
- updated a link to source code
> [DOCS-7816] removed outdated paragraph + updated link

- 404.html
- _config.yml
This PRs identifies the latest Alfresco documentation that has moved to the Hyland Documentation Portal (support.hyland.com).
Related:
- #1566
- #1571
> [DOCS-7865] Identify the latest migrated products

- process-services/latest/config/authenticate.md
- process-services/latest/develop/rest-api.md
> [MNT-24470] Basic Auth with Identity Services is no longer supported

- .gitignore
- 404.html
- _config.yml
- content-services/latest/install/ansible.md
- federation-services/latest/config/index.md
- microsoft-outlook/2.10/admin/index.md
- microsoft-outlook/latest/admin/index.md
- sync-service/4.0/support/index.md
- sync-service/latest/support/index.md
This PR adds the links to the Hyland Documentation Portal, using the new Alfresco landing page as a starting point. The links from previous releases are updated to match.
**Summary of changes**
- Add new documentation locations for Desktop Sync 1.19 / Sync Service 5.1 / Salesforce Connector 3.2 and higher
- Change links to new landing page: [support.hyland.com/p/alfresco](https://support.hyland.com/p/alfresco)
- List products in alphabetical order for easier look-up.
> [DOCS-7905] Add links to latest releases

- 404.html
- _config.yml
- Add banner for migrated Alfresco documentation
- Add link to the Hyland Documentation Portal
> [DOCS-8027] Add banner for migrated products
