Alfresco/docs-alfresco

- salesforce/latest/install/index.md
This correction was made in DOCS-6069.  Someone reverted the change.
> DOCS-6069 DOCS-6079

- _data/toc/content-services.yaml
- content-services/latest/develop/extension-inspector.md
Hi.
@gparapadakis I have added the extension inspector to the docs as per DOCS-6170.
Can you confirm you are ok with what is there?
For this JIRA https://alfresco.atlassian.net/browse/DOCS-6154 it appears as though you want me to add and then possibly subtract some things, could you be a bit more specific please?
Cheers
> [DOCS-6170] add extension inspector

- content-services/latest/develop/extension-inspector.md
The technical review has already been completed in #154 - this just improves the flow of the page
> [DOCS-6188] UA review for Extension Inspector

- _config.yml
- _data/toc/microsoft-office.yaml
- microsoft-office/1.3/admin/index.md
- microsoft-office/1.3/config/index.md
- microsoft-office/1.3/index.md
- microsoft-office/1.3/install/index.md
- microsoft-office/1.3/support/index.md
- microsoft-office/1.3/upgrade/index.md
- microsoft-office/1.3/using/index.md
- microsoft-office/latest/index.md
- microsoft-office/latest/install/index.md
- microsoft-office/latest/support/index.md
- microsoft-office/latest/upgrade/index.md
Changes approved in #139. This PR will be merged into master later in prep for the 7.0 release.
> [DOCS-6109] Microsoft Office 1.4

- content-services/community/install/ansible.md
- content-services/latest/install/ansible.md
This PR includes the changes requested in #172 (specifically, commit 9056a8e)
> [DOCS-6195] Update Ansible pages

- content-services/latest/support/index.md
> Add Amazon Corretto

- microsoft-365/1.0/install/index.md
- microsoft-365/1.0/using/faq.md
- microsoft-365/latest/index.md
- microsoft-365/latest/support/index.md
- microsoft-365/latest/using/index.md
Just sending this over to you to see if you can see this PR ?
> [DOCS-6124] 365 Connector

- search-services/latest/config/properties.md
solr.solrConnectTimeout was used for Solr 1. Refer https://alfresco.slack.com/archives/CANET0B55/p1618557980268600
> Property changed for Solr4/6

- microsoft-outlook/latest/config/index.md
> [DOCS-6221] Fix Send and Archive default folder option

- process-automation/latest/admin/monitor.md
- process-automation/latest/admin/release.md
- process-automation/latest/model/connectors/content.md
- process-automation/latest/model/interfaces.md
I have written:
- Added Add/Get Security Marks
- Audit Events and Triggers
- Delete a released project from the Admin App
- Save as Function
> WIP [DOCS-6176] add and get security marks]

- process-automation/latest/model/processes/index.md
Added text as per Release notes
Enhanced color codes for process diagram visualization:
blue for completed nodes,
green for current active nodes,
red for failed nodes
> [DOCS-6250] APA process visualization improved

- process-automation/latest/using/index.md
Added text about new notifications in ADW,
> [DOCS-6252]Task notification in adw

- process-automation/latest/develop/index.md
> [DOCS-6246] new rest api

- salesforce/latest/using/recommend.md
This documentation contained internal architecture information that should have never been published.  I've also cleaned up language that could be confusing to a Salesforce admin or imply functionality that is not supported.
> Fix Recommended Content Documentation

- salesforce/latest/install/index.md
Add missing visualforce page configuration steps.
> Visualforce page Configuration

- search-services/1.4/config/properties.md
- search-services/1.4/config/security.md
- search-services/latest/config/properties.md
- search-services/latest/config/security.md
added documentation for addressing https://nvd.nist.gov/vuln/detail/CVE-2020-13941
🆘 **DO NOT MERGE - wait for release approval**
> [MNT-22392] Docs update to address CVE-2020-13941

- salesforce/2.2/config/index.md
- salesforce/latest/config/index.md
- Update to provide links to Salesforce documentation
- Clarify setup.  Improve documentation examples.
> [MNT-22173] Update Salesforce Connector SSO Documentation

- transformation-engine/latest/install/index.md
Reverts Alfresco/docs-alfresco#295
> Revert "[DOCS-6110] adjustments to supported versions of office"

- transformation-engine/latest/install/index.md
Re reverted changes because they were not showing on staging for some reason.
> [DOCS-6315] corrections for revert

- _data/toc/insight-engine.yaml
- _data/toc/search-services.yaml
- insight-engine/latest/config/indexing.md
- search-services/latest/config/indexing.md
Added new page to SS and SIE docs. Also added new TOC entry cheers :-)
> [DOCS-6335] Indexing recommendations

- content-services/latest/support/index.md
- Initial commit to add 7.0.1 table in Supported Platforms page.
- Follow-up commits will update the supported services, integrations, and applications.
> [DOCS-6339] Update Supported Platforms page for ACS 7.0.1

- _config.yml
- _data/toc/federation-services.yaml
- content-services/6.0/support/index.md
- content-services/6.1/support/index.md
- content-services/6.2/support/index.md
- content-services/latest/support/index.md
- federation-services/1.1/admin/index.md
- federation-services/1.1/config/index.md
- federation-services/1.1/index.md
- federation-services/1.1/install/index.md
- federation-services/1.1/support/index.md
Created the new version 2.0
Added in new artefact references.
Updated SP pages on CS and AFS. Some were slightly incorrect.
> [DOCS-6357] Version and SP page updates

- _config.yml
- _data/toc/process-services.yaml
The 'latest' was mentioned twice in the .config file which was causing the issue.
> [DOCS-6358] fix for APS drop down issue

- _config.yml
- _data/toc/identity-service-tutorial.yaml
- _data/toc/identity-service.yaml
- identity-service/1.1/tutorial/sso/kerberos.md
- identity-service/1.3/tutorial/sso/kerberos.md
- identity-service/1.4/config/index.md
- identity-service/1.4/index.md
- identity-service/1.4/install/index.md
- identity-service/1.4/install/k8s/index.md
- identity-service/1.4/install/zip/index.md
- identity-service/1.4/support/index.md
- identity-service/1.4/tutorial/index.md
- identity-service/1.4/tutorial/sso/index.md
- identity-service/1.4/tutorial/sso/kerberos.md
- identity-service/1.4/tutorial/sso/ldap.md
- identity-service/1.4/tutorial/sso/saml.md
- identity-service/1.4/upgrade/index.md
- identity-service/latest/index.md
- identity-service/latest/tutorial/sso/kerberos.md
- identity-service/latest/upgrade/index.md
This PR was made because the review in this PR https://github.com/Alfresco/docs-alfresco/pull/291 meant I would need to revert some files. It was easier to create a new PR and apply the suggested changes to it. This is that PR.
> [DOCS-6303] Identity service v1.5

- search-enterprise/latest/index.md
Rewrote: search-enterprise/latest/index.md 
This is the only page that requires review, the other pages are being reviewed using other PRs.
> [DOCS-6383] Rewrite review intro page

- microsoft-365/latest/install/index.md
Missing step for granting admin consent in the guide added.
> Update Alfresco Collaboration Connector for Microsoft 365

- microsoft-outlook/latest/support/index.md
This PR only updates the Outlook Integration docs. Separate PRs will address the updates needed in the ACS docs.
> [DOCS-6402] Update Supported platforms page for v2.8.1

- microsoft-365/latest/install/index.md
- microsoft-365/latest/support/index.md
Minor updates to installation and support pages
> [DOCS-6360] MS 365 1.1.1 version bump

- _config.yml
- _data/glossary.yaml
- _data/toc/sap-cloud.yaml
- sap-cloud/1.1/admin/index.md
- sap-cloud/1.1/config/cloud.md
- sap-cloud/1.1/config/index.md
- sap-cloud/1.1/index.md
- sap-cloud/1.1/install/index.md
- sap-cloud/1.1/support/index.md
- sap-cloud/latest/config/genericxchange.md
- sap-cloud/latest/index.md
- sap-cloud/latest/install/index.md
- sap-cloud/latest/support/index.md
This branch will be merged to `master` once the release has been approved for GA release
Specific changes for Content Connector for SAP Cloud 1.2:
- #384
- #390
> [DOCS-6364] Add Alfresco Content Connector for SAP Cloud 1.2 docs

- content-services/latest/admin/import-transfer.md
- content-services/latest/config/action.md
- content-services/latest/develop/sdk.md
- content-services/latest/install/zip/index.md
- content-services/latest/install/zip/tomcat.md
This update only addresses the wording in the Content Services 7.1 branch.
A future update will address changes in other product documentation.
> [DOCS-6410] Update how to access Downloads in Support Portal/Hyland Community

- _config.yml
- _data/toc/digital-workspace.yaml
- content-services/6.2/support/index.md
- content-services/latest/support/index.md
- digital-workspace/2.0/support/index.md
- digital-workspace/2.1/support/index.md
- digital-workspace/2.2/support/index.md
- digital-workspace/2.3/config/index.md
- digital-workspace/2.3/extensions/index.md
- digital-workspace/2.3/governance/archiving.md
- digital-workspace/2.3/governance/index.md
- digital-workspace/2.3/governance/records.md
- digital-workspace/2.3/index.md
- digital-workspace/2.3/install/containerized.md
- digital-workspace/2.3/install/index.md
- digital-workspace/2.3/install/other-webserver.md
- digital-workspace/2.3/install/tomcat.md
- digital-workspace/2.3/media/index.md
- digital-workspace/2.3/process/config.md
- digital-workspace/2.3/process/index.md
- digital-workspace/2.3/process/managing.md
- digital-workspace/2.3/process/starting.md
- digital-workspace/2.3/process/tasks.md
- digital-workspace/2.3/support/index.md
- digital-workspace/2.3/troubleshooting/index.md
- digital-workspace/latest/support/index.md
Made the 2.4 version.
Corrected supported platforms in the ADW branches and in the ACS branches, 6.2.2 and above.
ADW 2.4 is also included in PR #390
> [DOCS-6422] ADW 2.4 branch

- facebook/latest/install/index.md
- facebook/latest/support/index.md
These are the initial Facebook 1.0 connector docs. This is a new product.
> [DOCS-6438] - Facebook 1.0 docs

- content-services/6.1/support/index.md
- content-services/6.2/support/index.md
- content-services/7.0/support/index.md
- content-services/latest/support/index.md
- digital-workspace/1.5/support/index.md
- digital-workspace/1.6/support/index.md
- digital-workspace/2.0/support/index.md
- digital-workspace/2.1/support/index.md
- digital-workspace/2.2/support/index.md
- digital-workspace/2.3/support/index.md
- digital-workspace/latest/support/index.md
I have adjusted the ACS supported versions for ADW and ACS based on what is on here https://www.alfresco.com/services/subscription/technical-support/product-support-status
> [DOCS-6472] corrected supported ACS versions

- insight-engine/1.4/install/options.md
- insight-engine/latest/install/options.md
- insight-engine/latest/support/index.md
- search-services/1.4/install/options.md
- search-services/1.4/support/index.md
- search-services/latest/install/options.md
- search-services/latest/support/index.md
I have added in the new install path plus aligned these pages because they were slightly out of sync.
> [DOCS-6426] Added new install path

- support/latest/holidays.md
Remove all the holiday dates for local Support Centers as they're very outdated. Customers will need to check the published dates in Hyland Community.
> [DOCS-6477] Update Support Holiday Calendar

- process-automation/latest/model/index.md
- process-automation/latest/model/interfaces.md
The names of the new fields added do not seem to follow sentence case.
I have added them as they appear in the UI, cheers.
> [DOCS-6475] Added new parameters for the UI section

- _config.yml
- _data/toc/digital-workspace.yaml
- digital-workspace/2.4/config/index.md
- digital-workspace/2.4/extensions/index.md
- digital-workspace/2.4/governance/archiving.md
- digital-workspace/2.4/governance/index.md
- digital-workspace/2.4/governance/records.md
- digital-workspace/2.4/index.md
- digital-workspace/2.4/install/containerized.md
- digital-workspace/2.4/install/index.md
- digital-workspace/2.4/install/other-webserver.md
- digital-workspace/2.4/install/tomcat.md
- digital-workspace/2.4/media/index.md
- digital-workspace/2.4/process/config.md
- digital-workspace/2.4/process/index.md
- digital-workspace/2.4/process/managing.md
- digital-workspace/2.4/process/starting.md
- digital-workspace/2.4/process/tasks.md
- digital-workspace/2.4/support/index.md
- digital-workspace/2.4/troubleshooting/index.md
> [DOCS-6465] Digital Workspace 2.5

- _data/toc/transformation-engine.yaml
- transformation-engine/2.2/admin/index.md
- transformation-engine/2.2/config/index.md
- transformation-engine/2.2/install/sdk.md
- transformation-engine/2.2/using/index.md
- transformation-engine/latest/admin/index.md
- transformation-engine/latest/config/index.md
- transformation-engine/latest/install/index.md
- transformation-engine/latest/install/msi.md
- transformation-engine/latest/install/sdk.md
- transformation-engine/latest/support/index.md
- transformation-engine/latest/using/index.md
This PR includes updates for the DTE 2.3.1 release, and also corrections in the previous version (v2.2).
> [DOCS-6468] DTE 2.3.1 release updates

- content-services/community/develop/rest-api-guide/searching.md
Old documentation link:
https://hub.alfresco.com/t5/alfresco-content-services-blog/basic-content-reporting-using-the-5-2-1-search-api/ba-p/288718
> Update searching.md based on part of the old documentation

- content-services/7.0/admin/content-stores.md
- content-services/7.0/admin/multi-tenancy.md
- content-services/7.0/develop/repo-ext-points/content-stores.md
- content-services/latest/admin/content-stores.md
- content-services/latest/admin/multi-tenancy.md
- content-services/latest/develop/repo-ext-points/content-stores.md
- content-services/latest/install/zip/additions.md
Additional fixes are in PR #472
> [DOCS-6509] Remove Centera Connector references in ACS 7 docs

- process-automation/latest/model/processes/index.md
NOTE: Jira referenced in title has been updated to DOCS-6496.
See DOCS-6494 for more information.
> [DOCS-6496] Update Date property

- process-automation/latest/model/forms.md
The property in the UI is not written in sentence case. I have reused how it is written in the UI.
> DOCS-6491 - Add description of new property - Content Properties to display

- transformation-engine/latest/install/msi.md
- transformation-engine/latest/support/index.md
Update the DTE T-Engine required to v1.2.0
> [DOCS-6516] Update T-Engine version for DTE 2.3.1

- _config.yml
- _data/toc/desktop-sync.yaml
- desktop-sync/1.7/admin/index.md
- desktop-sync/1.7/config/index.md
- desktop-sync/1.7/index.md
- desktop-sync/1.7/install/index.md
- desktop-sync/1.7/support/index.md
- desktop-sync/1.7/upgrade/index.md
- desktop-sync/1.7/using/ags.md
- desktop-sync/1.7/using/app-icons.md
- desktop-sync/1.7/using/app-menu.md
- desktop-sync/1.7/using/faq.md
- desktop-sync/1.7/using/metadata.md
- desktop-sync/1.7/using/permissions.md
- desktop-sync/1.7/using/select-to-sync.md
- desktop-sync/1.7/using/sharing.md
- desktop-sync/1.7/using/sync-conflict-guide.md
- desktop-sync/1.7/using/versions.md
- desktop-sync/latest/admin/index.md
- desktop-sync/latest/config/index.md
- desktop-sync/latest/index.md
- desktop-sync/latest/install/index.md
- desktop-sync/latest/support/index.md
This PR incorporates features in the next release of Alfresco Desktop Sync. See the individual commits for more details.
> [DOCS-6512] Alfresco Desktop Sync 1.8

- microsoft-outlook/latest/config/index.md
Relates to "Extract attachments from files" archive option
> [DOCS-6623] Add storeFilesFromDesktop config option

- _data/toc/content-services.yaml
- content-services/7.1/develop/extension-inspector.md
- content-services/7.1/develop/rest-api-guide/folders-files.md
- content-services/latest/develop/rest-api-guide/cloud-storage-props.md
- content-services/latest/develop/rest-api-guide/folders-files.md
- content-services/latest/develop/rest-api-guide/install.md
- content-services/latest/develop/sdk.md
* SDK 4.4
* ReST API
* Storage Properties
* Direct Access URLs 
* Extension Inspector 1.2.1 jar file update
> [DOCS-6599] ACS 7.2 Developer section updates

- content-services/latest/install/ansible.md
- content-services/latest/install/containers/customize.md
- content-services/latest/install/containers/docker-compose.md
- content-services/latest/install/containers/helm.md
- content-services/latest/install/containers/index.md
- content-services/latest/install/zip/additions.md
- content-services/latest/install/zip/amp.md
- content-services/latest/install/zip/index.md
- content-services/latest/install/zip/tomcat.md
- transform-service/latest/install/index.md
Note that the Ansible changes are in PR #587
> [DOCS-6597] ACS 7.2 Installation section (except Ansible)

- content-services/latest/admin/content-stores.md
Summary of changes
- `content-services/latest/admin/content-stores/index.md` - updated in this PR
- `content-services/latest/support/` - addressed in [this commit](https://github.com/Alfresco/docs-alfresco/pull/552/commits/dd0bf2aa9e1acc523ffe8d345382e8eba62f0f8c) as part of ACS Supported Platforms PR #552 
- `content-services/latest/install/zip/additions.md` - addressed in PR #543
> [DOCS-6640] Glacier impact on ACS 7.2 docs

- microsoft-office/latest/support/index.md
Waiting on if Content Services 7.1 should be added
> [DOCS-6621] Alfresco Office Services 1.4.1

- aws-glacier/latest/config/index.md
- aws-glacier/latest/install/index.md
This completes the work started in PR #592
> [DOCS-6644] Fix links to ACS 7.1 in Glacier docs

- digital-workspace/latest/index.md
Relates to Glacier Connector feature changes starting from ACS 7.2 (see PRs #591, #592, and #595)
> [DOCS-6661] Fix ADW docs - remove mention of archived content

- content-services/6.0/admin/security.md
- content-services/6.1/admin/security.md
- content-services/7.0/admin/security.md
- content-services/7.1/admin/security.md
- content-services/community/admin/security.md
- content-services/latest/admin/security.md
This update completes the fixes related to PR #204
> [DOCS-6312] Correct csrf.filter.referer config in ACS docs

- _config.yml
- _data/toc/identity-service-tutorial.yaml
- _data/toc/identity-service.yaml
- identity-service/1.5/upgrade/index.md
- identity-service/1.6/config/index.md
- identity-service/1.6/index.md
- identity-service/1.6/install/index.md
- identity-service/1.6/install/k8s/index.md
- identity-service/1.6/install/zip/index.md
- identity-service/1.6/support/index.md
- identity-service/1.6/tutorial/index.md
- identity-service/1.6/tutorial/sso/index.md
- identity-service/1.6/tutorial/sso/kerberos.md
- identity-service/1.6/tutorial/sso/ldap.md
- identity-service/1.6/tutorial/sso/saml.md
- identity-service/1.6/upgrade/index.md
- identity-service/latest/config/index.md
- identity-service/latest/index.md
- identity-service/latest/install/k8s/index.md
- identity-service/latest/install/zip/index.md
- identity-service/latest/support/index.md
- identity-service/latest/tutorial/sso/ldap.md
- identity-service/latest/tutorial/sso/saml.md
- identity-service/latest/upgrade/index.md
This PR incorporates updates for the next release of Identity Service plus some maintenance fixes. See the individual commits for more details.
> [DOCS-6586] Identity Service 1.7

- content-services/5.2/develop/repo-ext-points/scheduled-jobs.md
- content-services/6.0/develop/repo-ext-points/scheduled-jobs.md
- content-services/6.1/develop/repo-ext-points/scheduled-jobs.md
- content-services/6.2/develop/repo-ext-points/scheduled-jobs.md
- content-services/7.0/develop/repo-ext-points/scheduled-jobs.md
- content-services/7.1/develop/repo-ext-points/scheduled-jobs.md
- content-services/latest/develop/repo-ext-points/scheduled-jobs.md
FreeMarker ${..} entries must be escaped in Spring context files as follows \$\{..\}
> [DOCS-6707] FreeMarker ${..} entries must be escaped in Spring context files

- process-automation/latest/using/index.md
Reverts Alfresco/docs-alfresco#613
> Revert "[DOCS-6692] - Remove unwanted process sentence"

- desktop-sync/latest/index.md
- desktop-sync/latest/using/app-menu.md
- Adds new feature to **Remove Local Content**.
- Adds release summary.
- Fixes minor corrections.
> [DOCS-6601] Add feature - Remove Local Content

- salesforce/latest/using/recommend.md
**Summary of changes:**
- Add new feature for a configurable link for the Recommended Content panel
- Minor fixes for UI items
> [DOCS-6578] Add configurable link for Recommended Content panel

- salesforce/latest/support/index.md
- salesforce/latest/using/recommend.md
This PR incorporates features in the next release of Alfresco Content Connector for Salesforce. See the individual commits for more details.
> [DOCS-6578] Alfresco Content Connector for Salesforce 2.3.4

- _config.yml
- _data/toc/desktop-sync.yaml
- desktop-sync/1.9/admin/index.md
- desktop-sync/1.9/config/index.md
- desktop-sync/1.9/index.md
- desktop-sync/1.9/install/index.md
- desktop-sync/1.9/support/index.md
- desktop-sync/1.9/upgrade/index.md
- desktop-sync/1.9/using/ags.md
- desktop-sync/1.9/using/app-icons.md
- desktop-sync/1.9/using/app-menu.md
- desktop-sync/1.9/using/faq.md
- desktop-sync/1.9/using/metadata.md
- desktop-sync/1.9/using/permissions.md
- desktop-sync/1.9/using/select-to-sync.md
- desktop-sync/1.9/using/sharing.md
- desktop-sync/1.9/using/sync-conflict-guide.md
- desktop-sync/1.9/using/versions.md
- desktop-sync/latest/index.md
- desktop-sync/latest/using/app-menu.md
This PR incorporates updates for the next release of Alfresco Desktop Sync. See the individual commits for more details.
ℹ️ The release summary in `/desktop-sync/latest/index.md` is updated by PR #629.
> [DOCS-6698] Alfresco Desktop Sync 1.10

- process-automation/latest/using/index.md
- transform-service/latest/config/index.md
- transform-service/latest/index.md
- transform-service/latest/install/index.md
- transform-service/latest/support/index.md
This is mostly a version bump.
> [DOCS-6690] ATS 1.5.2

- content-services/5.2/support/index.md
- content-services/6.0/support/index.md
- content-services/6.1/support/index.md
- content-services/6.2/support/index.md
- content-services/7.0/support/index.md
- content-services/7.1/support/index.md
- content-services/latest/support/index.md
This updates the ACS Supported platforms pages so that they're aligned with the individual services, integrations, and applications.
> [DOCS-6688] Update compatible versions in Supported platforms pages

- process-automation/latest/model/forms.md
Reverts Alfresco/docs-alfresco#653
These changes need to go live once APA 7.3 has gone live
> Revert "[DOCS-6732] - Add Groups Restriction"

- process-automation/latest/model/authentication.md
Reverts Alfresco/docs-alfresco#649
These changes need to go live once APA 7.3 has gone live
> Revert "[DOCS-6728] - Add validation message"

- process-automation/latest/model/interfaces.md
Reverts Alfresco/docs-alfresco#645
These changes need to go live once APA 7.3 has gone live
> Revert "[DOCS-6723] - Add new content/process"

- transform-service/1.2/install/index.md
- transform-service/1.3/install/index.md
- transform-service/1.4/install/index.md
- transform-service/latest/install/index.md
> [DOCS-6734] Updated sfs endpoint ATS Zip install config

- process-automation/latest/model/authentication.md
Reverts Alfresco/docs-alfresco#673
> [DOCS-6728] - Add validation message

- process-automation/latest/model/forms.md
Reverts Alfresco/docs-alfresco#674
Un-reverting this revert as it is now able to be merged to master.
> [DOCS-6732] - Add Groups Restriction

- content-services/7.0/support/index.md
- content-services/7.1/support/index.md
- content-services/latest/support/index.md
This PR completes the updates for the next release of Alfresco Desktop Sync 1.11 in PR #683 and #682.
> [DOCS-6760][DOCS-6772] Update for Desktop Sync 1.11 compatibility

- content-services/7.1/support/index.md
- content-services/latest/support/index.md
This PR completes the updates for the next release of Identity Service 1.8 in PR #680 and PR #679.
> [DOCS-6759][DOCS-6772] Update for Identity Service 1.8 compatibility

- salesforce/latest/support/index.md
This PR incorporates updates for the next release of the Salesforce Connector.
> [DOCS-6740] Alfresco Content Connector for Salesforce 2.3.5

- transform-service/latest/install/index.md
> [DOCS-6764] Adding the scheduler contract path property to SFS startup cmd line

- microsoft-outlook/latest/config/index.md
- microsoft-outlook/latest/index.md
This PR adds the dependent picklist feature in the Alfresco Outlook Integration release summary and configuration.
> [DOCS-6808] Add dependent picklist feature in Outlook Integration

- content-services/latest/support/index.md
Compatibility added for ACS 7.2.1 only
> Add Alfresco Collaboration Connector for Teams 1.1 compatibility

- content-services/latest/support/index.md
- microsoft-365/latest/support/index.md
> [DOCS-6827] Connector for Microsoft 365 1.1.3 new version

- microsoft-outlook/latest/config/index.md
- microsoft-outlook/latest/index.md
This PR incorporates updates for the next release of Alfresco Outlook Integration. See the individual commits for more details.
Related PRs:
- https://github.com/Alfresco/docs-alfresco/pull/743
> [DOCS-6752] Alfresco Outlook Integration 2.9.1

- content-services/7.0/support/index.md
- content-services/7.1/support/index.md
- content-services/latest/install/containers/docker-compose.md
- content-services/latest/support/index.md
- google-drive/latest/support/index.md
- microsoft-365/latest/support/index.md
- saml-module/latest/support/index.md
This PR incorporates updates for the next release of Alfresco Content Services. See the individual commits for more details.
> [DOCS-6803] [DOCS-6847] Alfresco Content Services 7.2.1

- mobile-workspace/latest/using/index.md
This is a first draft of the features in Mobile Workspace: New Folder, Move files. Rename files, and Scan files. Additional information requested has been added to the ticket.
> [DOCS-6823] Update New Folder, Move, Rename, Scan

- content-services/7.0/install/zip/index.md
- content-services/7.1/install/zip/index.md
- content-services/community/install/zip/index.md
- content-services/latest/install/zip/index.md
- transform-service/1.2/install/index.md
- transform-service/1.3/install/index.md
- transform-service/1.4/install/index.md
- transform-service/latest/install/index.md
Updates following on from PR #745 and PR #751
> [DOCS-6846][DOCS-6858] Fix broken link and minor corrections

- mobile-workspace/latest/using/index.md
Adding Tasks feature documentation, so far.
> [DOCS-6865] Mobile Workspace Tasks

- content-services/6.2/support/index.md
- content-services/7.0/support/index.md
- content-services/7.1/support/index.md
- content-services/latest/support/index.md
AMW is compatible with ACS 6.2 and up, confirmed with Lilian
> [DOCS-6912] Mobile Workspace 1.4 ACS SP compatibility

- _config.yml
- _data/toc/desktop-sync.yaml
- desktop-sync/1.12/admin/index.md
- desktop-sync/1.12/config/index.md
- desktop-sync/1.12/index.md
- desktop-sync/1.12/install/index.md
- desktop-sync/1.12/support/index.md
- desktop-sync/1.12/upgrade/index.md
- desktop-sync/1.12/using/ags.md
- desktop-sync/1.12/using/app-icons.md
- desktop-sync/1.12/using/app-menu.md
- desktop-sync/1.12/using/faq.md
- desktop-sync/1.12/using/metadata.md
- desktop-sync/1.12/using/permissions.md
- desktop-sync/1.12/using/select-to-sync.md
- desktop-sync/1.12/using/sharing.md
- desktop-sync/1.12/using/sync-conflict-guide.md
- desktop-sync/1.12/using/versions.md
- desktop-sync/latest/index.md
This PR incorporates updates for the next release of Alfresco Desktop Sync. See the individual commits for more details.
Related PRs:
- https://github.com/Alfresco/docs-alfresco/pull/762/
- https://github.com/Alfresco/docs-alfresco/pull/781/
> [DOCS-6859] Alfresco Desktop Sync 1.13

- process-automation/latest/admin/monitor.md
- process-automation/latest/develop/index.md
I have also brought over the Data clean up section to this page because it was added to an incorrect page in an earlier PR.
I have added more information to the intro paragraph also.
> [DOCS-6925] Add applications list section

- search-enterprise/latest/config/index.md
- search-enterprise/latest/support/index.md
Reverts Alfresco/docs-alfresco#724
> Revert "[DOCS-6813] Support for Opensearch"

- content-services/7.2/support/index.md
- content-services/latest/support/index.md
> [DOCS-6932] [DOCS-6972] Add Sync Service 3.8 compatibility with ACS

- _data/scopes.yaml
Add the search scope for the **Support Handbook** so you can easily filter the search results.
> [DOCS-6989] Add search scope for Support Handbook

- content-services/latest/develop/extension-inspector.md
Updated to new version 1.5 and removed trailing spaces
> [DOCS-6928] Extension Inspector 1.5 version bump

- content-services/latest/support/index.md
> [DOCS-6998] Update Salesforce Connector compatibility with ACS 7.3

- content-services/7.0/support/index.md
- content-services/7.1/support/index.md
- content-services/latest/support/index.md
> [DOCS-6974] Update Desktop Sync 1.13.1 compatibility with ACS

- content-services/7.1/develop/rest-api-guide/index.md
- content-services/7.2/develop/rest-api-guide/index.md
- content-services/latest/develop/rest-api-guide/index.md
> [MNT-22629] New "allow.unsecure.callback.jsonp" repo property

- _config.yml
- _data/toc/google-drive.yaml
- google-drive/3.2/config/index.md
- google-drive/3.2/index.md
- google-drive/3.2/install/index.md
- google-drive/3.2/support/index.md
- google-drive/latest/support/index.md
Version update to 3.3 and updated file names from 3.2.x to 3.3.x
> [DOCS-6938] Google Docs 3.3 version bump

- salesforce/latest/support/index.md
> [DOCS-6996] Update compatible ACS version for Salesforce Connector 2.3.x

- content-services/6.2/develop/repo-ext-points/permissions.md
- content-services/latest/develop/repo-ext-points/permissions.md
Add statement about embedded workflow user permissions
> [DOCS-6056] Update permissions for MNT-21638

- content-services/community/config/activemq.md
- content-services/community/config/repository.md
- content-services/community/install/zip/amp.md
- content-services/community/install/zip/index.md
- content-services/community/install/zip/tomcat.md
Updates so far for install and zip.
> [DOCS-6970] ACS 7.3 Community Updates

- content-services/latest/release/index.md
Waiting on 5.2 or 5.1 confirmation. Also, not sure why the Note box didn't format properly.
> [DOCS-6969] What's New update for ACS 7.3

- search-enterprise/latest/config/index.md
- search-enterprise/latest/support/index.md
This PR is a re do of the changes made in this PR https://github.com/Alfresco/docs-alfresco/pull/724.
I mistakenly merged #724 to master when it should have been merged to #837.
I reverted the changes of #724 with #842.
> [DOCS-6813] Add support for Opensearch

- governance-services/community/develop/index.md
- governance-services/community/install/docker.md
- governance-services/community/install/zip.md
> [DOCS-7006] Alfresco Governance Services 7.3 Community Edition

- content-services/6.2/config/repository.md
- content-services/7.0/config/repository.md
- content-services/7.1/config/repository.md
- content-services/7.2/config/repository.md
- content-services/latest/config/repository.md
> [DOCS-7015] Add properties to control JavaScript execution

- _config.yml
- _data/toc/microsoft-office.yaml
- microsoft-office/1.4/admin/index.md
- microsoft-office/1.4/config/index.md
- microsoft-office/1.4/index.md
- microsoft-office/1.4/install/index.md
- microsoft-office/1.4/support/index.md
- microsoft-office/1.4/upgrade/index.md
- microsoft-office/1.4/using/index.md
- microsoft-office/latest/config/index.md
- microsoft-office/latest/support/index.md
This PR incorporates updates for the next release of Alfresco Office Services. See the individual commits for more details.
Related PRs:
- https://github.com/Alfresco/docs-alfresco/pull/876
> [DOCS-6939] Alfresco Office Services 1.5

- _data/toc/identity-service-tutorial.yaml
- identity-service/latest/tutorial/index.md
- identity-service/latest/tutorial/sso-v1/index.md
- identity-service/latest/tutorial/sso-v1/kerberos.md
- identity-service/latest/tutorial/sso-v1/ldap.md
- identity-service/latest/tutorial/sso-v1/saml.md
- identity-service/latest/tutorial/sso/saml.md
This PR creates two versions of the Single Sign On Guide:
- Single Sign On (SSO) Guide v2 for Content Services 7.3 and above
- Single Sign On (SSO) Guide v1 for earlier versions
> [DOCS-6924] Create new version of SSO Guide for ACS 7.3

- _config.yml
- _data/toc/digital-workspace.yaml
- digital-workspace/2.9/develop/deploy.md
- digital-workspace/2.9/develop/manage.md
- digital-workspace/3.0/config/index.md
- digital-workspace/3.0/develop/deploy.md
- digital-workspace/3.0/develop/extensions.md
- digital-workspace/3.0/develop/index.md
- digital-workspace/3.0/develop/manage.md
- digital-workspace/3.0/governance/index.md
- digital-workspace/3.0/governance/records.md
- digital-workspace/3.0/governance/security.md
- digital-workspace/3.0/index.md
- digital-workspace/3.0/install/containerized.md
- digital-workspace/3.0/install/index.md
- digital-workspace/3.0/install/other-webserver.md
- digital-workspace/3.0/install/tomcat.md
- digital-workspace/3.0/media/index.md
- digital-workspace/3.0/process/config.md
- digital-workspace/3.0/process/index.md
- digital-workspace/3.0/process/managing.md
- digital-workspace/3.0/process/starting.md
- digital-workspace/3.0/process/tasks.md
- digital-workspace/3.0/support/index.md
- digital-workspace/3.0/troubleshooting/index.md
- digital-workspace/latest/develop/deploy.md
- digital-workspace/latest/develop/manage.md
- digital-workspace/latest/support/index.md
- digital-workspace/latest/troubleshooting/index.md
This PR incorporates updates for the next release of Alfresco Digital Workspace. See the individual commits for more details.
> [DOCS-6934] Alfresco Digital Workspace 3.1

- _config.yml
- _data/toc/aws-s3.yaml
- aws-s3/5.0/config/direct-access.md
- aws-s3/5.0/config/index.md
- aws-s3/5.0/index.md
- aws-s3/5.0/install/index.md
- aws-s3/5.0/support/index.md
- aws-s3/5.0/upgrade/index.md
- aws-s3/5.0/using/faq.md
- aws-s3/latest/index.md
- aws-s3/latest/support/index.md
- aws-s3/latest/using/faq.md
Updates for ACS 7.3 compatibility and Java 17 support.
> [DOCS-6941] Updates for Alfresco Content Connector for AWS S3 5.1

- _config.yml
- _data/toc/transform-service.yaml
- transform-service/1.5/admin/index.md
- transform-service/1.5/config/add-tengine-trouter.md
- transform-service/1.5/config/index.md
- transform-service/1.5/index.md
- transform-service/1.5/install/index.md
- transform-service/1.5/support/index.md
- transform-service/latest/install/index.md
- transform-service/latest/support/index.md
Initial changes pushed to GitHub for 2.0.
> [DOCS-6936] Updates for Alfresco Transform Service 2.0

- process-services/latest/admin/index.md
- process-services/latest/support/index.md
Waiting for confirmation on support updates
> [DOCS-6981] Alfresco Process Services 2.3.5 Fixed typos

- content-services/latest/install/containers/docker-compose.md
- Added new properties in tables for Content App and Control Center.
- Updated image versions.
> [DOCS-7030] Alfresco Content Services 7.3 Enterprise Trial updates

- _config.yml
- _data/toc/federation-services.yaml
- federation-services/1.0/support/index.md
- federation-services/1.1/support/index.md
- federation-services/2.0/admin/index.md
- federation-services/2.0/config/index.md
- federation-services/2.0/index.md
- federation-services/2.0/install/index.md
- federation-services/2.0/support/index.md
- federation-services/latest/support/index.md
This PR incorporates updates for the next release of Alfresco Federation Services. See the individual commits for more details.
Related:
- #916
> [DOCS-6696] Alfresco Federation Services 2.1

- saml-module/latest/index.md
Also adds links to the Supported platforms pages so you can review the compatible versions
> [DOCS-6950] Fix link to SSO Guide for SAML 1.2

- desktop-sync/1.14/index.md
- desktop-sync/latest/index.md
- desktop-sync/latest/using/app-menu.md
- desktop-sync/latest/using/faq.md
This PR adds and updates the following information:
- Windows: [Alfresco Docs - Application menu in taskbar](https://docs.alfresco.com/desktop-sync/latest/using/app-menu/#menu/windows/manage-your-account) 
- re-order application menus under **Manage Your Account** 
- add new feature: **Account Information**
- Mac: [Alfresco Docs - Application menu in taskbar](https://docs.alfresco.com/desktop-sync/latest/using/app-menu/#menu/mac/settings)
- re-order application menus under **Settings** and move submenus under **Manage Your Account** 
- add new feature: **Account Information**
> [DOCS-7188] Add UI indicators for space consumed by Alfresco folder

- microsoft-365/1.1/install/index.md
- microsoft-365/latest/install/index.md
- microsoft-365/latest/support/index.md
Updated image versions, supported platforms, and download link.
> [DOCS-7211] 365-edits

- content-services/latest/admin/cluster.md
Add documentation to the cluster section describing important actions required to harden the cluster and prevent exposing sensitive data.
> [DOCS-7213] ACS 7.4 Admin - Hazelcast security

- _config.yml
- _data/toc/microsoft-office.yaml
- microsoft-office/1.5/admin/index.md
- microsoft-office/1.5/config/index.md
- microsoft-office/1.5/index.md
- microsoft-office/1.5/install/index.md
- microsoft-office/1.5/support/index.md
- microsoft-office/1.5/upgrade/index.md
- microsoft-office/1.5/using/index.md
- microsoft-office/latest/support/index.md
This PR incorporates updates for the next release of Alfresco Office Services (AOS). See the individual commits for more details.
Related:
- #976
> [DOCS-7085] Add Alfresco Office Services (AOS) 1.6 docs

- _config.yml
- _data/toc/salesforce.yaml
- salesforce/2.3/config/index.md
- salesforce/2.3/index.md
- salesforce/2.3/install/index.md
- salesforce/2.3/support/index.md
- salesforce/2.3/using/community.md
- salesforce/2.3/using/index.md
- salesforce/2.3/using/recommend.md
- salesforce/2.3/using/troubleshoot.md
- salesforce/latest/config/index.md
- salesforce/latest/install/index.md
- salesforce/latest/support/index.md
This PR incorporates updates for the next release of Alfresco Content Connector for Salesforce. See the individual commits for more details.
Related:
- #967 
- #975
> [DOCS-7084] Add Alfresco Content Connector for Salesforce 2.4 docs

- _data/toc/content-services.yaml
- content-services/latest/admin/control-center.md
- content-services/latest/using/content/tags-categories.md
This PR moves the commits in PR #993 related to the ACS 7.4 changes so they'll appear in the upcoming ACS 7.4 documentation.
> [DOCS-7237] Add Tags and Categories feature to ACS 7.4 docs

- _config.yml
- _data/toc/digital-workspace.yaml
- content-services/latest/admin/control-center.md
- digital-workspace/3.1/config/index.md
- digital-workspace/3.1/develop/deploy.md
- digital-workspace/3.1/develop/extensions.md
- digital-workspace/3.1/develop/index.md
- digital-workspace/3.1/develop/manage.md
- digital-workspace/3.1/governance/index.md
- digital-workspace/3.1/governance/records.md
- digital-workspace/3.1/governance/security.md
- digital-workspace/3.1/index.md
- digital-workspace/3.1/install/containerized.md
- digital-workspace/3.1/install/index.md
- digital-workspace/3.1/install/other-webserver.md
- digital-workspace/3.1/install/tomcat.md
- digital-workspace/3.1/media/index.md
- digital-workspace/3.1/process/config.md
- digital-workspace/3.1/process/index.md
- digital-workspace/3.1/process/managing.md
- digital-workspace/3.1/process/starting.md
- digital-workspace/3.1/process/tasks.md
- digital-workspace/3.1/support/index.md
- digital-workspace/3.1/troubleshooting/index.md
- digital-workspace/latest/config/index.md
- digital-workspace/latest/governance/security.md
- digital-workspace/latest/index.md
- digital-workspace/latest/support/index.md
Related PRs
- https://github.com/Alfresco/docs-alfresco/pull/1009
> [DOCS-7181] Alfresco Digital Workspace 4.0

- content-services/community/install/zip/amp.md
- content-services/community/install/zip/index.md
- content-services/community/install/zip/tomcat.md
- content-services/latest/upgrade/index.md
Use show rich diff, as only changes were "7.3" to "7.4".
> [DOCS-7191] Updated community ZIP file links to 7.4

- enterprise-viewer/latest/install/index.md
Please verify the additions are in the correct location in the documentation.
> [DOCS 7038] Add AEV secureBrowserCookies

- _data/toc/enterprise-viewer.yaml
- enterprise-viewer/latest/install/index.md
- enterprise-viewer/latest/install/java-support.md
- enterprise-viewer/latest/install/prereqs.md
- enterprise-viewer/latest/install/upgrade.md
- enterprise-viewer/latest/support/index.md
> [DOCS-7139] Alfresco Enterprise Viewer 3.5.1

- support/latest/policies/hotfix.md
- TAM can request a Hot Fix
- update ACS version to a supported version
> Hotfix for TAM and version update

- _data/toc/content-accelerator.yaml
- content-accelerator/latest/install/sso.md
- content-accelerator/latest/install/upgrading.md
Related update (to be merged into this PR):
-  #1041
> [DOCS-7231] Add new optional SSO implementation for ACA 3.5.1

- microsoft-teams/latest/support/index.md
Adding platforms from this comment: https://github.com/Alfresco/docs-alfresco/pull/1024#pullrequestreview-1441640490.
> [DOCS-7210] Update Teams 2.0 Supported Platforms

- _config.yml
- _data/toc/desktop-sync.yaml
- desktop-sync/1.15/admin/index.md
- desktop-sync/1.15/config/index.md
- desktop-sync/1.15/index.md
- desktop-sync/1.15/install/index.md
- desktop-sync/1.15/support/index.md
- desktop-sync/1.15/upgrade/index.md
- desktop-sync/1.15/using/ags.md
- desktop-sync/1.15/using/app-icons.md
- desktop-sync/1.15/using/app-menu.md
- desktop-sync/1.15/using/faq.md
- desktop-sync/1.15/using/metadata.md
- desktop-sync/1.15/using/permissions.md
- desktop-sync/1.15/using/select-to-sync.md
- desktop-sync/1.15/using/sharing.md
- desktop-sync/1.15/using/sync-conflict-guide.md
- desktop-sync/1.15/using/versions.md
- desktop-sync/latest/index.md
- desktop-sync/latest/support/index.md
- desktop-sync/latest/using/app-menu.md
This PR incorporates updates for the next release of Alfresco Desktop Sync. See the individual commits for more details.
Related:
- #1054 
- #1055
> [DOCS-7251] Alfresco Desktop Sync 1.16 docs

- content-services/7.1/support/index.md
- microsoft-teams/1.1/support/index.md
Change Teams Connector 1.1 compatibility to ACS 7.1 - 7.3
> [DOCS-7209] Fix Teams 1.1 ACS 7.3 support

- aws-s3/latest/support/index.md
- content-accelerator/latest/support/index.md
- desktop-sync/latest/support/index.md
- federation-services/latest/support/index.md
- google-drive/latest/support/index.md
- insight-engine/latest/support/index.md
- microsoft-azure/latest/support/index.md
- microsoft-office/latest/support/index.md
- saml-module/latest/support/index.md
- search-enterprise/latest/support/index.md
- search-services/latest/support/index.md
This PR removes the **Alfresco Content Services** heading and formats the content into a single table.
> [DOCS-6914] Consistency updates for Supported platforms pages

- transformation-engine/2.3/config/index.md
- transformation-engine/2.3/install/msi.md
- transformation-engine/latest/config/index.md
- transformation-engine/latest/install/index.md
- transformation-engine/latest/install/msi.md
- transformation-engine/latest/install/sdk.md
- transformation-engine/latest/support/index.md
This PR includes a few maintenance fixes to clean-up the docs, as well as updates for the latest release.
> [DOCS-7307] Update install, config, and support sections of DTE 2.4 docs

- _config.yml
- _data/toc/transformation-engine.yaml
- transformation-engine/2.3/admin/index.md
- transformation-engine/2.3/config/index.md
- transformation-engine/2.3/index.md
- transformation-engine/2.3/install/index.md
- transformation-engine/2.3/install/msi.md
- transformation-engine/2.3/install/sdk.md
- transformation-engine/2.3/support/index.md
- transformation-engine/2.3/using/index.md
- transformation-engine/latest/config/index.md
- transformation-engine/latest/install/index.md
- transformation-engine/latest/install/msi.md
- transformation-engine/latest/install/sdk.md
- transformation-engine/latest/support/index.md
This PR incorporates updates for the next release of Alfresco Document Transformation Engine and some maintenance fixes. See the individual commits for more details.
Related:
- #1096 
- #1101
> [DOCS-7307] Add Alfresco Document Transformation Engine 2.4 docs

- content-services/latest/admin/security.md
introduced by https://alfresco.atlassian.net/browse/ACS-4759
> [DOCS-7362] Update security.md

- search-enterprise/3.2/support/index.md
- search-enterprise/latest/support/index.md
This was accidentally reverted as part of #837.
> [DOCS-7369] Reinclude support for Opensearch.

- _config.yml
- _data/toc/sap.yaml
- sap/5.2/admin/index.md
- sap/5.2/admin/reference.md
- sap/5.2/config/advanced.md
- sap/5.2/config/index.md
- sap/5.2/index.md
- sap/5.2/install/index.md
- sap/5.2/support/index.md
- sap/5.2/upgrade/index.md
- sap/latest/admin/reference.md
- sap/latest/index.md
- sap/latest/install/index.md
- sap/latest/support/index.md
This PR incorporates updates for the next release of Alfresco Content Connector for SAP Applications. See the individual commits for more details.
Related:
- #1104 
- #1138
> [DOCS-7312] Add Alfresco Content Connector for SAP Applications 5.3 docs

- content-services/7.0/support/index.md
- content-services/7.1/support/index.md
- content-services/7.2/support/index.md
- content-services/7.3/support/index.md
- content-services/latest/support/index.md
This PR has the following changes:
- Update compatible versions in Alfresco Content Services 7.0-7.4 Supported platforms pages
- #1144 
- #1146
> [DOCS-7354] Update Content Services Supported platforms pages

- content-services/7.1/develop/reference/java-foundation-ref.md
- content-services/7.2/develop/reference/java-foundation-ref.md
- content-services/7.3/develop/reference/java-foundation-ref.md
- content-services/latest/develop/reference/java-foundation-ref.md
Transformer is no more part of contentService
> [DOCS-7326] Updated the sample code for transformation

- search-enterprise/3.0/using/index.md
- search-enterprise/3.1/using/index.md
- search-enterprise/latest/using/index.md
Add reference to pre-indexing considerations for exact term search
> [DOCS-7203] Add reference to pre-indexing considerations

- _config.yml
- _data/toc/aws-s3.yaml
- aws-s3/5.1/config/direct-access.md
- aws-s3/5.1/config/index.md
- aws-s3/5.1/index.md
- aws-s3/5.1/install/index.md
- aws-s3/5.1/support/index.md
- aws-s3/5.1/upgrade/index.md
- aws-s3/5.1/using/faq.md
- aws-s3/latest/config/index.md
- aws-s3/latest/index.md
- aws-s3/latest/install/index.md
- aws-s3/latest/support/index.md
This PR incorporates updates for the next release of Alfresco Content Connector for AWS S3. See the individual commits for more details.
- #1179 
- #1188
> [DOCS-7406] Add Alfresco Content Connector for AWS S3 6.0 Docs

- _config.yml
- _data/toc/microsoft-azure.yaml
- microsoft-azure/3.2/admin/index.md
- microsoft-azure/3.2/config/direct-access.md
- microsoft-azure/3.2/config/index.md
- microsoft-azure/3.2/index.md
- microsoft-azure/3.2/install/index.md
- microsoft-azure/3.2/support/index.md
- microsoft-azure/latest/config/index.md
- microsoft-azure/latest/index.md
- microsoft-azure/latest/install/index.md
- microsoft-azure/latest/support/index.md
This PR incorporates updates for the next release of Alfresco Content Connector for Azure. See the individual commits for more details.
- #1176 
- #1189
> [DOCS-7385] Add Alfresco Content Connector for Azure 4.0 docs

- content-services/latest/config/repository.md
This is one of many PRs that will include the changes from PR  #1168
Related PRs:
- #1168
- #1195 
- #1198
> [DOCS-7446] Update supported version of Tomcat in Config docs

- content-services/latest/install/ansible.md
- content-services/latest/install/containers/customize.md
- content-services/latest/install/containers/docker-compose.md
- content-services/latest/install/containers/helm.md
- content-services/latest/install/zip/additions.md
- content-services/latest/install/zip/amp.md
- content-services/latest/install/zip/index.md
- content-services/latest/install/zip/tomcat.md
This PR includes installation updates for:
- Tomcat 10 upgrade
- Release artefacts
- Supported stack changes
> [DOCS-7415] Update Install pages

- _config.yml
- _data/toc/sap.yaml
- sap/5.3/admin/index.md
- sap/5.3/admin/reference.md
- sap/5.3/config/advanced.md
- sap/5.3/config/index.md
- sap/5.3/index.md
- sap/5.3/install/index.md
- sap/5.3/support/index.md
- sap/5.3/upgrade/index.md
- sap/latest/admin/reference.md
- sap/latest/install/index.md
- sap/latest/support/index.md
This PR incorporates updates for the next release of Alfresco Content Connector for SAP Applications. See the individual commits for more details.
> [DOCS-7386] Add Alfresco Content Connector for SAP Applications 6.0

- content-accelerator/latest/install/install-guide.md
- content-accelerator/latest/support/index.md
- content-services/7.2/support/index.md
- content-services/7.3/support/index.md
- content-services/7.4/support/index.md
This pull request includes three commits. Two commits for the Support page and one commit is related to the DOCS-7124 task (related to "Update Content Accelerator install configurations for Install guide."
> [DOCS-7433] Update ACA 3.6 compatibility with ACS and configuration

- content-accelerator/latest/install/install-guide.md
This task also includes some changes related to DOCS-7124
> [DOCS-7448] Update ACA install guide

- content-services/7.0/admin/license.md
- content-services/7.1/admin/license.md
- content-services/7.2/admin/license.md
- content-services/7.3/admin/license.md
- content-services/7.4/admin/license.md
- content-services/latest/admin/license.md
This PR updates the links added by PR #1181 so that customers are routed to their licensing page.
> [DOCS-7463] Fix links to Hyland Community - Licensing pages

- _config.yml
- _data/toc/enterprise-viewer.yaml
- content-services/7.2/support/index.md
- content-services/7.3/support/index.md
- content-services/7.4/support/index.md
- enterprise-viewer/3.5/config/actions.md
- enterprise-viewer/3.5/config/collaboration.md
- enterprise-viewer/3.5/config/faq.md
- enterprise-viewer/3.5/config/files.md
- enterprise-viewer/3.5/config/overlay.md
- enterprise-viewer/3.5/config/performance.md
- enterprise-viewer/3.5/config/suggested-redact.md
- enterprise-viewer/3.5/config/supported-languages.md
- enterprise-viewer/3.5/develop/adf.md
- enterprise-viewer/3.5/develop/integrations.md
- enterprise-viewer/3.5/index.md
- enterprise-viewer/3.5/install/adf.md
- enterprise-viewer/3.5/install/aevt.md
- enterprise-viewer/3.5/install/index.md
- enterprise-viewer/3.5/install/java-support.md
- enterprise-viewer/3.5/install/prereqs.md
- enterprise-viewer/3.5/install/upgrade.md
- enterprise-viewer/3.5/support/index.md
- enterprise-viewer/3.5/using/index.md
- enterprise-viewer/latest/config/actions.md
- enterprise-viewer/latest/config/files.md
- enterprise-viewer/latest/install/index.md
- enterprise-viewer/latest/install/upgrade.md
- enterprise-viewer/latest/support/index.md
This PR incorporates updates for the next release of Alfresco Enterprise Viewer. See the individual commits for more details.
> [DOCS-7136] Add Alfresco Enterprise Viewer 3.6

- search-enterprise/3.3/using/unsupported.md
- search-enterprise/latest/using/unsupported.md
This PR updates the compatibility between Alfresco Content Accelerator, Alfresco Enterprise Viewer, and Alfresco Search Enterprise (versions 3.3 and 4.0).
> [DOCS-7450] Update ACA and AEV compatibility with Alfresco Search Enterprise

- _config.yml
- _data/toc/federation-services.yaml
- content-services/latest/support/index.md
- federation-services/3.0/admin/index.md
- federation-services/3.0/config/index.md
- federation-services/3.0/index.md
- federation-services/3.0/install/index.md
- federation-services/3.0/support/index.md
- federation-services/latest/install/index.md
- federation-services/latest/support/index.md
This PR incorporates updates for the next release of Alfresco Federation Services. See the individual commits for more details.
> [DOCS-7442] Add Alfresco Federation Service 3.1

- identity-service/latest/support/index.md
- microsoft-365/latest/support/index.md
- microsoft-teams/latest/support/index.md
- sap-cloud/latest/support/index.md
- transformation-engine/latest/support/index.md
This PR updates the Supported platforms pages so they're in line with the [Alfresco Product Support Status page](https://www.alfresco.com/services/subscription/technical-support/product-support-status).
> [DOCS-7475] Fix Support status for existing releases

- search-enterprise/latest/using/languages.md
Fixed typo in URL to CMIS spec.
> [DOCS-7502] Correct https error in link

- process-services/latest/install/manual.md
Add a note: In manual install step 5.3. you need to manually create the path, otherwise upload to actiiti will fail with the error:
```
java.lang.NullPointerException: Cannot read the array length because "<local6>" is null
at com.activiti.content.storage.fs.FileSystemContentStorage.getMaxChild(FileSystemContentStorage.java:311) ~[content-storage-fs-2.4.0.jar:2.4.0]
at com.activiti.content.storage.fs.FileSystemContentStorage.getFirstAvailableFolder(FileSystemContentStorage.java:238) ~[content-storage-fs-2.4.0.jar:
2.4.0]```
> [DOCS-7504] Update manual.md

- search-enterprise/3.2/using/languages.md
- search-enterprise/3.3/using/languages.md
Corrected the link in language.md file for search-enterprise version 3.3 and 3.2
> [DOCS-7502]-Correct https error in link

- microsoft-outlook/latest/index.md
ℹ️ The final reviews will be addressed in the release branch - #1123
> [DOCS-7494] Update release summary

- transformation-engine/latest/config/index.md
> [DOCS-7527] Typo in DTE Config index.md

- transformation-engine/2.3/config/index.md
This PR completes the updates started in PR #1268
> [DOCS-7527] Fix typo in DTE 2.3 Config index.md

- content-services/latest/support/index.md
as in our zip distribution we ship that jar
> [DOCS-7531] Add Postgresql JDBC for ACS 23.1

- process-automation/latest/model/connectors/rest.md
> [DOCS-7521] REST output parameter changed

- content-services/latest/admin/cluster.md
Ref: DOCS-7547
Changes has been tested in https://github.com/Alfresco/alfresco-helm-charts/pull/207
> DOCS-7547 Bump custom application context for share clustering

- process-services/2.3/config/database.md
- process-services/latest/config/database.md
> Revert "[MNT-23709] Clarify Hibernate Settings"

- content-services/7.4/support/index.md
- content-services/latest/support/index.md
Added supported vanilla Keycloak version for ACS 7.4 and ACS 23.1
> [DOCS-7575] Fix/keycloak compatibility

- process-automation/latest/model/triggers.md
Ref: https://alfresco.atlassian.net/browse/HXPDOC-8002
> Add secured parameter for INCOMING_WEBHOOK

- search-enterprise/3.3/admin/index.md
- search-enterprise/latest/admin/index.md
This pull request includes the Bulk metadata indexing topic in Enterprise Search 3.3 and 4.0, which is already published in Enterprise Search 3.2.
> [DOCS-7517] Enterprise Search fast metadata indexing

- content-services/latest/support/index.md
> [DOCS-7600] Fix AIS compatibility for ACS 23.x

- content-services/7.3/support/index.md
- content-services/7.4/support/index.md
- content-services/latest/support/index.md
> [DOCS-7510] Update note for Keycloak compatibility

- insight-engine/latest/install/options.md
Updated the Download Trial link in the Insight Engine (latest) version
> [DOCS-7667] Update Download Trial link in Insight Engine

- content-services/7.4/support/index.md
- process-services/2.4/config/authenticate.md
- process-services/2.4/support/index.md
Relates to:
-  #1477 
-  #1478
> [DOCS-7677] Add Keycloak to ACS 7.4.2 and APS 2.4 SP

- _config.yml
- _data/toc/desktop-sync.yaml
- desktop-sync/1.17/admin/index.md
- desktop-sync/1.17/config/index.md
- desktop-sync/1.17/index.md
- desktop-sync/1.17/install/index.md
- desktop-sync/1.17/support/index.md
- desktop-sync/1.17/upgrade/index.md
- desktop-sync/1.17/using/ags.md
- desktop-sync/1.17/using/app-icons.md
- desktop-sync/1.17/using/app-menu.md
- desktop-sync/1.17/using/faq.md
- desktop-sync/1.17/using/metadata.md
- desktop-sync/1.17/using/permissions.md
- desktop-sync/1.17/using/select-to-sync.md
- desktop-sync/1.17/using/sharing.md
- desktop-sync/1.17/using/sync-conflict-guide.md
- desktop-sync/1.17/using/versions.md
- desktop-sync/latest/index.md
- desktop-sync/latest/install/index.md
- desktop-sync/latest/support/index.md
- desktop-sync/latest/using/faq.md
- desktop-sync/latest/using/select-to-sync.md
This PR incorporates updates for the next release of Alfresco Desktop Sync. See the individual commits for more details.
Related:
- #1480 
- #1502
- #1499 
- #1500
- #1501
> [DOCS-7709] Add Alfresco Desktop Sync 1.18 docs

- sync-service/3.11/support/index.md
- Split compatibility for each ACS version across multiple rows
- Update compatible versions based on the latest information
> [DOCS-7723] Updates ACS compatibility for Sync Service 3.11.3

- content-services/7.3/admin/auth-sync.md
- content-services/7.3/support/index.md
⚠️ Follow-up fix: `content-services/7.3/admin/auth-sync.md`
Fix link in the above file for the `aims.resource` property for Keycloak once PR is merged.
> [DOCS-7690] Add Alfresco Content Services 7.3.2 docs

- content-services/7.3/admin/auth-sync.md
> [DOCS-7681] Fix missing link in 7.3 auth-sync.md

- _data/toc/content-services.yaml
> [DOCS-7727] Add ACS 7.2 Configure Keycloak page to TOC

- search-enterprise/3.0/config/index.md
- search-enterprise/3.1/config/index.md
- search-enterprise/3.2/config/index.md
- search-enterprise/3.3/config/index.md
Merged the changes @MattioliLeo suggested in latest. Included the changes in previous versions, 3.0 to 3.3 of Search Enterprise.
> [DOCS-7722] Typo in mediation-filter.yml example

- process-services/latest/install/manual.md
Updating the link to request a license for Alfresco customers.
> [DOCS-7773] Update manual.md

- content-services/7.2/support/index.md
- content-services/7.3/support/index.md
- content-services/7.4/support/index.md
Reverts Alfresco/docs-alfresco#1575 - incorrect Supported Platforms update
> Revert "[DOCS-7851] Update ACS Supported Platforms"

- _config.yml
- _data/home.yaml
- _includes/migrated_banner.html
- _layouts/docs.html
- _layouts/home.html
- assets/css/main.css
This PR adds a banner to identify the latest Alfresco documentation that has  moved to the Hyland Documentation Portal.
> [DOCS-7831] Add notification for migration

- 404.html
- _config.yml
- Add banner for migrated Alfresco Outlook Integration documentation
- Add link to the Hyland Documentation Portal
> [DOCS-7991] Add banner for migrated Alfresco Outlook Integration

- 404.html
- _config.yml
- Add banner for migrated Alfresco documentation
- Add link to the Hyland Documentation Portal
> [DOCS-8097] Add banner for migrated products
